### ISSUE TITLE
go 1.6 concurrent map bugs

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1052]
In the transfer queue:

```
fatal error: bad map state

goroutine 186 [running]:
runtime.throw(0x90d660, 0xd)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:527 +0x90 fp=0xc823bd9ce8 sp=0xc823bd9cd0
runtime.evacuate(0x7b49a0, 0xc8210203f0, 0x7)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/hashmap.go:825 +0x3b1 fp=0xc823bd9da8 sp=0xc823bd9ce8
runtime.growWork(0x7b49a0, 0xc8210203f0, 0x10)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/hashmap.go:795 +0x83 fp=0xc823bd9dc8 sp=0xc823bd9da8
runtime.mapdelete(0x7b49a0, 0xc8210203f0, 0xc823bd9e40)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/hashmap.go:525 +0xb9 fp=0xc823bd9e28 sp=0xc823bd9dc8
github.com/github/git-lfs/lfs.(*ProgressMeter).FinishTransfer(0xc823449200, 0xc8207567a9, 0x31)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/progress_meter.go:84 +0x6d fp=0xc823bd9e58 sp=0xc823bd9e28
github.com/github/git-lfs/lfs.(*TransferQueue).transferWorker(0xc82102e0d0)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/transfer_queue.go:290 +0x376 fp=0xc823bd9f98 sp=0xc823bd9e58
runtime.goexit()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc823bd9fa0 sp=0xc823bd9f98
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
        /Users/rick/go/src/github.com/github/git-lfs/lfs/transfer_queue.go:322 +0x167
```

**Comment by technoweenie** [comment]
Doh, this is the one I fixed already in https://github.com/github/git-lfs/commit/9024843eb8c97e6388699b4f5c7110f04d26d655.
