### ISSUE TITLE
Test TestExistingUpload depends on running in a git working-copy, dirties .git/lfs/objects

### ISSUE THREAD

**Issue by javabrett** [github/git-lfs#1202]
[TestExistingUpload](https://github.com/github/git-lfs/blob/master/lfs/upload_test.go#L16) is working with local storage, and is depending on running within a git repository.  This prevents building from a source-tarball (#1201).

It is also then polluting the local git-lfs working-copy's Git LFS object store with a test-artifact in the form of `.git/lfs/objects/98/88/988881adc9fc3655077dc2d4d757d480b5ea0e11`.

Build failure in from-tarball-source build:

```
=== RUN   TestSSHGetExeAndArgsTortoisePlinkCustomPort
--- PASS: TestSSHGetExeAndArgsTortoisePlinkCustomPort (0.00s)
=== RUN   TestExistingUpload
--- FAIL: TestExistingUpload (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6fb88d]

goroutine 281 [running]:
panic(0x8cf640, 0xc82000e170)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8201ea750)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x8cf640, 0xc82000e170)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/github/git-lfs/localstorage.localObjectDir(0x0, 0x9ec1a0, 0x28, 0x0, 0x0)
	<redacted>/go/src/github.com/github/tmp/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/localstorage/localstorage.go:57 +0x19d
github.com/github/git-lfs/localstorage.(*LocalStorage).BuildObjectPath(0x0, 0x9ec1a0, 0x28, 0x0, 0x0, 0x0, 0x0)
	<redacted>/go/src/github.com/github/tmp/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/localstorage/localstorage.go:48 +0x6e
github.com/github/git-lfs/lfs.LocalMediaPath(0x9ec1a0, 0x28, 0x0, 0x0, 0x0, 0x0)
	<redacted>/go/src/github.com/github/tmp/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/lfs.go:57 +0x4f
github.com/github/git-lfs/lfs.TestExistingUpload(0xc8201ea750)
	<redacted>/go/src/github.com/github/tmp/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/upload_test.go:109 +0x4f5
testing.tRunner(0xc8201ea750, 0xdc03a0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
FAIL	github.com/github/git-lfs/lfs	0.112s
?   	github.com/github/git-lfs/localstorage	[no test files]
?   	github.com/github/git-lfs/script	[no test files]
?   	github.com/github/git-lfs/subprocess	[no test files]
dh_auto_test: go test -v github.com/github/git-lfs github.com/github/git-lfs/commands github.com/github/git-lfs/docs/man github.com/github/git-lfs/git github.com/github/git-lfs/lfs github.com/github/git-lfs/localstorage github.com/github/git-lfs/script github.com/github/git-lfs/subprocess returned exit code 1
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory `<redacted>/go/src/github.com/github/tmp/git-lfs'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

After running in a proper Git LFS working-copy:

```
cat .git/lfs/objects/98/88/988881adc9fc3655077dc2d4d757d480b5ea0e11 
test
```

Reference commit efdcb06b856b248c99c9374b835f9331ff3ba97b .

**Comment by javabrett** [comment]
Looks like integration tests know how to use a `GIT_LFS_TEST_DIR`, but the unit test suite does not.

**Comment by technoweenie** [comment]
Good catch. It should probably run git stuff in a temp directory.

**Comment by javabrett** [comment]
This is harder to fix than it looks, for me anyway.  The first problems seem to be in [upload_test.go](https://github.com/github/git-lfs/blob/master/lfs/upload_test.go) , which does not seem to use temp repos e.g. from `NewRepo`.  The problem with just importing and using that is that it creates the `lfs` -> `test` -> `lfs` import-cycle.  And if you try and move `upload_test.go` into `lfs_test` as has been done elsewhere, you find that it relies on a bunch of unexported consts/structs in `lfs`.
