### ISSUE TITLE
lfs_test: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ignatenkobrain** [github/git-lfs#1219]
```
+ go test -compiler gc -ldflags '' github.com/github/git-lfs/lfs
warning: current Git remote contains credentials
warning: current Git remote contains credentials
--- FAIL: TestExistingUpload (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6fb1ad]

goroutine 205 [running]:
panic(0x893100, 0xc82000a190)
	/usr/lib/golang/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc8205fc5a0)
	/usr/lib/golang/src/testing/testing.go:467 +0x192
panic(0x893100, 0xc82000a190)
	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
github.com/github/git-lfs/localstorage.localObjectDir(0x0, 0x9a66a0, 0x28, 0x0, 0x0)
	/home/brain/rpmbuild/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/localstorage/localstorage.go:57 +0x19d
github.com/github/git-lfs/localstorage.(*LocalStorage).BuildObjectPath(0x0, 0x9a66a0, 0x28, 0x0, 0x0, 0x0, 0x0)
	/home/brain/rpmbuild/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/localstorage/localstorage.go:48 +0x6e
github.com/github/git-lfs/lfs.LocalMediaPath(0x9a66a0, 0x28, 0x0, 0x0, 0x0, 0x0)
	/home/brain/rpmbuild/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/lfs/lfs.go:57 +0x4f
github.com/github/git-lfs/lfs.TestExistingUpload(0xc8205fc5a0)
	/home/brain/rpmbuild/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/lfs/upload_test.go:109 +0x4f5
testing.tRunner(0xc8205fc5a0, 0xd62040)
	/usr/lib/golang/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:582 +0x892
FAIL	github.com/github/git-lfs/lfs	0.062s
```

**Comment by ignatenkobrain** [comment]
I started tests from tarball (not git repo), once I did `git init` it started working... I think it's still bug.

**Comment by javabrett** [comment]
Duplicates #1202, see also #1201. LFS is known to not currently build from a source tarball, as there are unit tests that are accidentally relying on running from within a git repo, rather thsn creating a temp one.

**Comment by technoweenie** [comment]
Thanks for reporting, this should be fixed on master now. If you still have issues, can you reply with more details?
