### ISSUE TITLE
Fix error which happen due to hitting our storage quota

### ISSUE THREAD

**Issue by dotnetCarpenter** [github/git-lfs#1302]
We hit our storage quota and bought an extra pack. But I still can not move images between repositories.

### In the new repository
When I try to `pull` from our old repository I get the following error:

```
git pull old master
From https://github.com/Firefund/styleguide
 * branch            master     -> FETCH_HEAD
Downloading assets/image/18.jpg (53.04 KB)
Error downloading object: assets/image/18.jpg (d219eb98d8b615d71277cb36c6f728456dc62d9df5b98852cde5542c070fb1b9)

Errors logged to /home/dotnet/projects/firefund/frontend/.git/lfs/objects/logs/20160613T225448.709404218.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: assets/image/18.jpg: smudge filter lfs failed
```

`git lfs logs last`

```
git lfs logs last
git-lfs/1.2.0 (GitHub; linux amd64; go 1.5.3)
git version 2.7.4

$ git-lfs pull
Error updating the git index


exit status 1
goroutine 52 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7fae0558b330, 0xc82007e1d8, 0x7fae0558cb10, 0xc82007e1b0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:195 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7fae0558cb10, 0xc82007e1b0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:159 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7fae0558cb10, 0xc82007e1b0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:134 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7fae0558cb10, 0xc82007e1b0, 0x97a220, 0x1f, 0xc82004fe68, 0x1, 0x1)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:84 +0x82
github.com/github/git-lfs/commands.checkoutWithChan(0xc820067e60)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:229 +0xa72
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc820067e60, 0xc820104020)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x21
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x439

ENV:
LocalWorkingDir=/home/dotnet/projects/firefund/styleguide
LocalGitDir=/home/dotnet/projects/firefund/styleguide/.git
LocalGitStorageDir=/home/dotnet/projects/firefund/styleguide/.git
LocalMediaDir=/home/dotnet/projects/firefund/styleguide/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/dotnet/projects/firefund/styleguide/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
```

### In the old repository
I have removed all images with `git rm --cached assets/image/*`, made a commit, pushed it to master, re-added the images, checked with `git lfs status` that they are tracked, committed and pushed to master.

**Comment by dotnetCarpenter** [comment]
I tried to force upload of images to git lfs but hit another error.

`echo “refs/heads/master {commit}  refs/heads/master 0000000000000000000000000000000000000000” | GIT_TRACE=1 git lfs pre-push origin`

yields:
```
19:04:42.656936 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin'
19:04:42.657044 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin'
trace git-lfs: run_command: git rev-list --objects {commit} --not refs/remotes/origin/KM4REAL refs/remotes/origin/csi_grid refs/remotes/origin/gh-pages refs/remotes/origin/gzip refs/remotes/origin/huge_fixes refs/remotes/origin/lineheight refs/remotes/origin/master refs/remotes/origin/review-all-buttons --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
Error scanning for Git LFS files
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l

Errors logged to /home/dotnet/projects/firefund/styleguide/.git/lfs/objects/logs/20160614T190446.483005819.log
```

`git lfs logs last` yields:
```
git-lfs/1.2.1 (GitHub; linux amd64; go 1.5.3)
git version 2.7.4

$ git-lfs pre-push origin
Error scanning for Git LFS files

Error in git rev-list --objects: exit status 128 19:04:46.478611 git.c:344               trace: built-in: git 'rev-list' '--objects' '{commit}' '--not' 'refs/remotes/origin/KM4REAL' 'refs/remotes/origin/csi_grid' 'refs/remotes/origin/gh-pages' 'refs/remotes/origin/gzip' 'refs/remotes/origin/huge_fixes' 'refs/remotes/origin/lineheight' 'refs/remotes/origin/master' 'refs/remotes/origin/review-all-buttons' '--'
fatal: bad revision '{commit}'

goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7ffa750e4330, 0xc82002e008, 0x7ffa750e0000, 0xc820102a70)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:197 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7ffa750e0000, 0xc820102a70, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:161 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7ffa750e0000, 0xc820102a70, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:136 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7ffa750e0000, 0xc820102a70, 0x98d260, 0x20, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:86 +0x82
github.com/github/git-lfs/commands.Panic(0x7ffa750e0000, 0xc820102a70, 0x98d260, 0x20, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:96 +0x5d
github.com/github/git-lfs/commands.prePushCommand(0xd6e5c0, 0xc820069e70, 0x1, 0x1)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_pre_push.go:78 +0x66b
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xd6e5c0, 0xc820069dc0, 0x1, 0x1, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xd6fc80, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:101 +0x23
main.main()
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=/home/dotnet/projects/firefund/styleguide
LocalGitDir=/home/dotnet/projects/firefund/styleguide/.git
LocalGitStorageDir=/home/dotnet/projects/firefund/styleguide/.git
LocalMediaDir=/home/dotnet/projects/firefund/styleguide/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/dotnet/projects/firefund/styleguide/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
GIT_TRACE=1
```

**Any suggestions for a fix?!?**

**Comment by dotnetCarpenter** [comment]
## Perhaps error between git lfs versions
My team mate just updated an image which was checked into git and not git lfs. He is using git lfs 1.2.0 on darwin amd64. First he removed it from git, made a commit and then re-added it to git lfs. He did `git lfs install` before all of that to make sure the hook was in order.

```
Merge made by the 'recursive' strategy.
 assets/image/team3.JPG | Bin 2775354 -> 132 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
```

When I do `git lfs fetch` I get:
```
git lfs fetch
Fetching master
Git LFS: (0 of 29 files) 0 B / 6.55 MB                                                                                                        
Git LFS: (0 of 29 files) 0 B / 6.55 MB

$ cat assets/image/team3.JPG 
version https://git-lfs.github.com/spec/v1
oid sha256:21048d7d781821dd805cc2f760b1a0b1dd34fe095a84c4626b70f741b44d818b
size 2775354
```

**Comment by technoweenie** [comment]
1. What's the error in `20160613T225448.709404218.log`. My hunch is that the smudge filter failed due to some network or local io issue, but `git lfs logs last` gave the failure of the `git lfs pull` command.
2. Passed a bad commit: `fatal: bad revision '{commit}'`
3. What does your `.gitattributes` look like? I wonder if you need to track `*.JPG` for `assets/image/team3.JPG`?

**Comment by dotnetCarpenter** [comment]
@technoweenie sorry but we already moved past git-lfs. It didn't work for us.

**Comment by DavidLP** [comment]
I have this issue and I did not exceed the quota. All binary files have 132  bytes after checkout.

**Comment by dotnetCarpenter** [comment]
@DavidLP did you try `git lfs fetch origin`?

**Comment by dotnetCarpenter** [comment]
Or `git lfs pull origin master`
