### ISSUE TITLE
git lfs clean causes panic - bug

### ISSUE THREAD

**Issue by MaciejKucia** [github/git-lfs#1347]
Sadly another issue to report in.
```
$ git lfs clean
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4bc7b9]

goroutine 1 [running]:
panic(0x9133c0, 0xc08200a0b0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3f4
github.com/github/git-lfs/commands.requireStdin(0xa586a0, 0x34)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:118 +0x49
github.com/github/git-lfs/commands.cleanCommand(0xc582c0, 0xc7b9b0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_clean.go:18 +0x75
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc582c0, 0xc7b9b0, 0x0, 0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc5b6c0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:101 +0x2a
main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135
```

```
$ git lfs env
git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
git version 2.9.0.windows.1

Endpoint=https://artifactory (auth=basic)
LocalWorkingDir=C:\Repo\Stash\repo_X
LocalGitDir=C:\Repo\Stash\repo_X\.git
LocalGitStorageDir=C:\Repo\Stash\repo_X\.git
LocalMediaDir=C:\Repo\Stash\repo_X\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Repo\Stash\repo_X\.git\lfs\tmp
ConcurrentTransfers=5
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Notable environment state in addition to a few modified files:
```
$ git status
HEAD detached at  e68cd85
```

**Comment by ttaylorr** [comment]
Hi, @MaciejKucia -- thanks for opening this issue, and sorry about the unexpected panic 😦.

I just submitted a pull request that will fix this issue in the future: see https://github.com/github/git-lfs/pull/1349. If the problem still persists after we merge that in and release it, please let me know! 👋

**Comment by ttaylorr** [comment]
Awesome, #1349 is merged in, and this problem should be no more!
