### ISSUE TITLE
git-lfs smudge crashes

### ISSUE THREAD

**Issue by NiklasRosenstein** [github/git-lfs#1366]
Just tried to checkout a repository from GitLab that uses GitLFS, the download of first object failed immediately. The log is

```
λ cat "C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases\.git\lfs\objects\logs\20160713T155201.7828857.log"
git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
git version 2.9.0.windows.1

$ git-lfs.exe smudge -- Anim_Cam_path_T1.c4d
Error downloading object: Anim_Cam_path_T1.c4d (03b2513cda7681bfa6159fbd8d26e56b0c236247d38b493a4afd1c2287d6f748)

exit status 1
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:566 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x29642c0, 0xc082110008, 0x2e342b8, 0xc08210a0e0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:197 +0xf87
github.com/github/git-lfs/commands.logPanic(0x2e342b8, 0xc08210a0e0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:161 +0x419
github.com/github/git-lfs/commands.handlePanic(0x2e342b8, 0xc08210a0e0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:136 +0x55
github.com/github/git-lfs/commands.LoggedError(0x2e342b8, 0xc08210a0e0, 0xa2a560, 0x21, 0xc08207dc78, 0x2, 0x2)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:86 +0x89
github.com/github/git-lfs/commands.smudgeCommand(0xc5a680, 0xc0820fc640, 0x1, 0x2)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:79 +0xdd4
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc5a680, 0xc0820fc4a0, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc5b6c0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:101 +0x2a
main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases
LocalGitDir=C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases\.git
LocalGitStorageDir=C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases\.git
LocalMediaDir=C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
GIT_DIR=.git
GIT_LFS_PATH=F:\Git LFS
```

Running the smudge command manually gives a traceback as well but a different one.

```
λ git-lfs.exe smudge -- Anim_Cam_path_T1.c4d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4bc7b9]

goroutine 1 [running]:
panic(0x9133c0, 0xc082008090)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3f4
github.com/github/git-lfs/commands.requireStdin(0xa586e0, 0x35)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:118 +0x49
github.com/github/git-lfs/commands.smudgeCommand(0xc5a680, 0xc08212e5e0, 0x1, 0x2)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:23 +0x42
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc5a680, 0xc08212e440, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc5b6c0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:101 +0x2a
main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135
```

Version:

````
λ git lfs version
git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
```

**Comment by NiklasRosenstein** [comment]
Similar with v1.2.0

```
λ git-lfs.exe smudge -- Anim_Cam_path_T1.c4d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4bb839]

goroutine 1 [running]:
panic(0x90f100, 0xc082008090)
        C:/Go/src/runtime/panic.go:464 +0x3f4
github.com/github/git-lfs/commands.requireStdin(0xa53c80, 0x35)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:116 +0x49
github.com/github/git-lfs/commands.smudgeCommand(0xc52680, 0xc08212c5e0, 0x1, 0x2)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_smudge.go:23 +0x42
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc52680, 0xc08212c440, 0x2, 0x2, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc536c0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:99 +0x2a
main.main()
        C:/Users/techn/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135
```

**Comment by technoweenie** [comment]
Thanks for the report. You're not intended to be using the `smudge` command directly. Try just `git lfs pull`.

The nil pointer error is something that should be fixed, but it won't solve your problem.

**Comment by NiklasRosenstein** [comment]
Thanks for the fast reply. The output is pretty inconsistent but the pulling doesn't work no matter how often I try.

``` 
C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases (master)
λ git lfs pull
Git LFS: (0 of 142 files) 0 B / 258.10 MB
C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases (master)
λ git lfs pull
Git LFS: (0 of 142 files) 0 B / 258.10 MB
exit status 1
exit status 1

C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases (master)
λ git lfs pull

C:\maxon\Cinema 4D R16 Dev\plugins\vray-testsuite\testcases (master)
λ git lfs pull
Git LFS: (0 of 142 files) 0 B / 258.10 MB
exit status 1
```

**Comment by technoweenie** [comment]
Try it with `GIT_TRACE=1`. That should print out more details on what the tool is doing. `GIT_CURL_VERBOSE=1` will print out the actual http requests and responses as well.

**Comment by elventear** [comment]
@NiklasRosenstein  FWIW I was running into a similar issue and was able to work around, not sure if this is your exact issue. 

I am working on Linux, and I was using alternate SSH keys using a clone call like this:

```> GIT_SSH_COMMAND='ssh -i ~/.ssh/alternate_key' git clone git@github.com:my_repo.git```

Git would clone successfully but git-lfs would error out with similar tracebacks to the one you had. I simlinked `alternate_key` to `id_rsa` (the default key used by ssh) and I was able to clone and do git-lfs without issues. I would like at how you are specifying your SSH keys.

**Comment by ttaylorr** [comment]
@NiklasRosenstein are you still having this issue?

**Comment by NiklasRosenstein** [comment]
Using `GIT_TRACE=1` gives

```
[..truncated..]
trace git-lfs: ssh: download attempted with git@thedomain.com.  Error: exit status 1
trace git-lfs: tq: sending batch of size 42
trace git-lfs: ssh: git@thedomain.com git-lfs-authenticate laublab/auto_tests.git download
trace git-lfs: ssh: download attempted with git@thedomain.com.  Error: exit status 1
```

There seems to be no additional output produced when I set `GIT_CURL_VERBOSE=1`.

@elventear Thanks, but I don't think this would be a solution here. The only key that is set up on the remote is my standard (and only) SSH key, and cloning the repository works fine.

@ttaylorr Yes. I tried getting more info from SSH, but neither setting `GIT_SSH_COMMAND="ssh -v"` nor setting the loglevel in `~/.ssh/config` worked.

    Host thedomain.com
        LogLevel DEBUG3

Could it be a GitLab issue?

**Comment by technoweenie** [comment]
Try running `ssh git@thedomain.com git-lfs-authenticate laublab/auto_tests.git download`. If it returns some JSON, then it works. If not, then gitlab doesn't support LFS over SSH. That trace message mentions "exit status 1", so I don't think it's supported.
