### ISSUE TITLE
Upload error - should we add a retry logic?

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1393]
While uploading many individual LFS files I ran into this error twice now:

```
git-lfs/1.2.0 (GitHub; linux amd64; go 1.6.1; git 9bd3b8e)
git version 2.9.0.12.g05f1b67

$ git-lfs push --object-id origin 0b8b01ec8834e9fd79f11dba203a3dea3d8f12cd1d71a272856b2cff4069b122
Server Error
Docs: https://help.github.com/enterprise

Server Error
Docs: https://help.github.com/enterprise
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7fa7734aa358, 0xc820026110, 0x7fa7734c13d0, 0xc8203f4a40)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:195 +0xf80
github.com/github/git-lfs/commands.logPanic(0x7fa7734c13d0, 0xc8203f4a40, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:159 +0x412
github.com/github/git-lfs/commands.handlePanic(0x7fa7734c13d0, 0xc8203f4a40, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:134 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7fa7734c13d0, 0xc8203f4a40, 0xc8203c50c0, 0x35, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:84 +0x82
github.com/github/git-lfs/commands.upload(0xc820011b10, 0xc820026158, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/uploader.go:143 +0xb98
github.com/github/git-lfs/commands.uploadsWithObjectIDs(0xc820011b10, 0xc82010e760, 0x1, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_push.go:75 +0x210
github.com/github/git-lfs/commands.pushCommand(0xc41520, 0xc82010e750, 0x2, 0x3)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_push.go:156 +0x53a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc41520, 0xc82010e6c0, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3f4
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc42700, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:99 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=/.../git-repo
LocalGitDir=/.../git-repo/.git
LocalGitStorageDir=/.../git-repo/.git
LocalMediaDir=/.../git-repo/.git/lfs/objects
LocalReferenceDir=
TempDir=/.../git-repo/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
```

I don't think it is a LFS problem. I think it is a network or server glitch. Would it make sense to add some kind of retry logic here? https://github.com/github/git-lfs/blob/9bd3b8e8ccde93628938e9573999d25df539691d/commands/uploader.go#L124-L139

Maybe this could be configured using a Git config like `lfs.retry = 3`?

Thanks,
Lars

**Comment by ttaylorr** [comment]
Sounds like a good idea, if I'm understanding your issue correctly. Do you mean to add retry logic to the upload itself, or to the batch request sent to determine where to upload? If you mean the former, than I am all for it. If, on the other hand, you were referring to the later, that sort of logic [already exists](https://github.com/github/git-lfs/blob/7baff5624d2a76ce9c7a5d64bd53a96cfeb6d544/transfer/adapterbase.go#L131).

**Comment by ttaylorr** [comment]
This was added in v1.4.2.
