### ISSUE TITLE
`git lfs clone` fails to fetch LFS files and exists with error

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1408]
Hi,

I saw this error today with stock Git 2.9 and Git-LFS 1.2.0. The error happened during a `git lfs clone` operation here:
https://github.com/github/git-lfs/blob/386c5d81cac75b67fa36d033b8d246f53a71c2c7/commands/command_fetch.go#L123

The repository in question has *a lot* of LFS files. Any idea what went wrong and how I can debug this?

Thanks,
Lars

```
git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.1)
git version 2.9.0

$ git-lfs pull
Error
Request ID: afce372e-57e2-11e6-824f-4892529d65c7

Error
Request ID: afce372e-57e2-11e6-824f-4892529d65c7
goroutine 40 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0xf44308, 0xc821522060, 0xfa4be8, 0xc8227438d0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:195 +0xf80
github.com/github/git-lfs/commands.logPanic(0xfa4be8, 0xc8227438d0, 0x0, 0x0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:159 +0x412
github.com/github/git-lfs/commands.handlePanic(0xfa4be8, 0xc8227438d0, 0x0, 0x0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:134 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xfa4be8, 0xc8227438d0, 0xc8211ef900, 0x36, 0x0, 0x0, 0x0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:84 +0x82
github.com/github/git-lfs/commands.Panic(0xfa4be8, 0xc8227438d0, 0xc8211ef900, 0x36, 0x0, 0x0, 0x0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:94 +0x5d
github.com/github/git-lfs/commands.ExitWithError(0xfa4be8, 0xc8227438d0)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:62 +0x156
github.com/github/git-lfs/commands.fetchAndReportToChan(0xc82033c000, 0x26d6, 0x3000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820178000, ...)
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/command_fetch.go:312 +0x675
created by github.com/github/git-lfs/commands.fetchRefToChan
	/private/tmp/git-lfs20160418-2500-19m8yqb/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/command_fetch.go:123 +0x16c

ENV:
LocalWorkingDir=/redacted
LocalGitDir=/redacted/.git
LocalGitStorageDir=/redacted/.git
LocalMediaDir=/redacted/.git/lfs/objects
LocalReferenceDir=
TempDir=/redacted/.git/lfs/tmp
ConcurrentTransfers=10
BatchTransfer=true
GIT_PREFIX=
```

**Comment by technoweenie** [comment]
That looks like a response from your LFS server. Can you try running `GIT_CURL_VERBOSE=1 git lfs clone`? 

Would be nice if LFS added the http request info to error logs like this...

**Comment by larsxschneider** [comment]
OK, I will retry this call. The server is GHE... is there a way to learn about the error in the GHE logs?

**Comment by technoweenie** [comment]
Look for `afce372e-57e2-11e6-824f-4892529d65c7` in `/data/alambic/shared/log/alambic.log`. This will probably give you some internal GHE error, so I'd highly recommend going through GHE Support if you have to do more digging. They can help better if it's a GHE problem, or rope my team in if it's LFS specific.

**Comment by larsxschneider** [comment]
For the record `zgrep "<<REQUEST_ID>>" /var/log/alambic/*` is the right command.  I passed all other info to GHE support. Please see #34910

**Comment by technoweenie** [comment]
Closing this, it's a server issue.
