### ISSUE TITLE
Issue when using with github enterprise server.

### ISSUE THREAD

**Issue by dtiesling** [github/git-lfs#276]
I'm getting the following error when I'm attempting to use git-lfs with a github enterprise server. Is this an error or am I using it incorrectly?

```
Post https://[REDACTED].git/info/lfs/objects: x509: certificate signed by unknown authority
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/commands.logPanic(0x668890, 0xc208298b10, 0x69da00, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:156 +0xf17
github.com/github/git-lfs/commands.handlePanic(0x668890, 0xc208298b10, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:108 +0x6c
github.com/github/git-lfs/commands.LoggedError(0x668890, 0xc208298b10, 0xc2082ddbd0, 0x4f, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:65 +0x89
github.com/github/git-lfs/commands.prePushCommand(0x594800, 0xc208044660, 0x2, 0x2)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands_pre_push.go:97 +0x63f
github.com/spf13/cobra.(*Command).execute(0x594800, 0xc208044640, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x594700, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x594700, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

**Comment by technoweenie** [comment]
GitHub Enterprise installs with a self-signed cert initially.  It's up to you to install a cert for your install's domain that's not trusted by the enterprise instance.  Here's a help guide for it: https://help.github.com/enterprise/2.2/admin/articles/troubleshooting-ssl-errors/#removing-the-passphrase-from-your-key-file

You can tell Git and Git LFS to ignore SSL cert verification errors too.  You can disable it for individual commands:

    $ GIT_SSL_NO_VERIFY=1 git clone ...

You can also configure individual repositories to ignore verification errors.

    $ git config http.sslverify false
    $ git clone ...
