### ISSUE TITLE
How to get downloads working with ssh-auth and the lfs reference server?

### ISSUE THREAD

**Issue by quinox** [github/git-lfs#279]
I managed to get `git-lfs` partially working, uploading works just fine but I'm not sure how to get the downloading working. The asymmetry of this problem is throwing me off so I hope you can shed some light on this issue.

Looking at the logs it seems that for uploading files `git-lfs` only does 1 POST to the server - since it succeeds I suppose it's using the credentials as provided by SSH. Retrieving files causes two GETs, of which the first one works (HTTP 200) and the second one fails (HTTP 401). 

If the error is accurate this would suggest the client isn't using the credentials as provided by SSH for the second request. At this point I don't know what should have happened:
* The client should have used the same credetials (bug in the client)
* The server should have echo'd back the credentials for further requests (bug in the server)
* ...something else?

## Setup ##

* `git-lfs` is version 0.5.1
* `lfs-test-server` is version 0.5.1
* The git repo has a `.gitattributes` sending all PSDs into LFS
* There is *no* lfs.url specified anywhere
* The git server always returns the same output for `git-lfs-authenticate`:
```json
{
  "header": {
    "Authorization": "Basic ...hashed-credentials...=="
  },
  "href": "http://odin.ytec.nl:12345/ytec/lfsrepo"
}
```

## Downloading, console output ##

```php
quinox@duivenkracht:~/tmp$ GIT_TRACE=2 git clone git@odin.ytec.nl:testing; 
13:15:44.847823 git.c:349               trace: built-in: git 'clone' 'git@odin.ytec.nl:testing'
Cloning into 'testing'...
13:15:44.851179 run-command.c:341       trace: run_command: 'ssh' 'git@odin.ytec.nl' 'git-upload-pack '\''testing'\'''
13:15:45.605459 run-command.c:341       trace: run_command: 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 30510 on duivenkracht' '--check-self-contained-and-connected'
13:15:45.605801 exec_cmd.c:134          trace: exec: 'git' 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 30510 on duivenkracht' '--check-self-contained-and-connected'
13:15:45.607432 git.c:349               trace: built-in: git 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 30510 on duivenkracht' '--check-self-contained-and-connected'
remote: Counting objects: 249, done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 249 (delta 126), reused 0 (delta 0)
Receiving objects: 100% (249/249), 4.31 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... 13:15:46.735424 run-command.c:341       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
13:15:46.735767 exec_cmd.c:134          trace: exec: 'git' 'rev-list' '--objects' '--stdin' '--not' '--all'
13:15:46.737644 git.c:349               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
done.
13:15:46.741353 run-command.c:341       trace: run_command: 'git lfs smudge '\''basiliq/basiliq.psd'\'''
13:15:46.741698 run-command.c:192       trace: exec: '/bin/sh' '-c' 'git lfs smudge '\''basiliq/basiliq.psd'\''' 'git lfs smudge '\''basiliq/basiliq.psd'\'''
13:15:46.743836 git.c:554               trace: exec: 'git-lfs' 'smudge' 'basiliq/basiliq.psd'
13:15:46.743913 run-command.c:341       trace: run_command: 'git-lfs' 'smudge' 'basiliq/basiliq.psd'
trace git-lfs: run_command: 'git' version
Downloading basiliq/basiliq.psd (18.07 MB)
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' config -l -f .gitconfig
trace git-lfs: ssh: git@odin.ytec.nl git-lfs-authenticate testing download 6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c
trace git-lfs: HTTP: GET http://odin.ytec.nl:12345/ytec/lfsrepo/objects/6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: GET http://odin.ytec.nl:12345/ytec/lfsrepo/objects/6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c
trace git-lfs: HTTP: 401
Error accessing media: basiliq/basiliq.psd (6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c)

Errors logged to /home/quinox/tmp/testing/.git/lfs/objects/logs/20150503T131547.55799622.log.
```

## Trace log ##

```php
> git-lfs smudge basiliq/basiliq.psd
LocalWorkingDir=/home/quinox/tmp/testing
LocalGitDir=/home/quinox/tmp/testing/.git
LocalMediaDir=/home/quinox/tmp/testing/.git/lfs/objects
TempDir=/home/quinox/tmp/testing/.git/lfs/tmp
GIT_DIR=.git
GIT_TRACE=2

Error accessing media: basiliq/basiliq.psd (6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c)

Error downloading /home/quinox/tmp/testing/.git/lfs/objects/6e/9c/6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c.
Authorization error: http://odin.ytec.nl:12345/ytec/lfsrepo/objects/6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c
Check that you have proper access to the repository
Status=401 Unauthorized
Request:Www-Authenticate=Basic realm=git-lfs-server
Response:User-Agent=git-lfs/0.5.1 (GitHub; linux amd64; git 2.1.0; go 1.3)
URL=GET http://odin.ytec.nl:12345/ytec/lfsrepo/objects/6e9cee1e8b3156f9002c2391bece1df87bcbaa7581a908833920a53842b5d94c
Response:Accept=application/vnd.git-lfs
Request:Date=Sun, 03 May 2015 11:15:47 GMT
Request:Content-Length=12
Request:Content-Type=text/plain; charset=utf-8
Endpoint=https://odin.ytec.nl/testing.git/info/lfs
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/lfs.Errorf(0x7f4d3dcd51b0, 0xc208001b00, 0x79c160, 0x0, 0x0, 0x0, 0x0, 0xb8)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:29 +0x62
github.com/github/git-lfs/lfs.Error(0x7f4d3dcd51b0, 0xc208001b00, 0xc2080a56b0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:17 +0x52
github.com/github/git-lfs/lfs.defaultError(0xc20802f680, 0x71fbe0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:363 +0x151
github.com/github/git-lfs/lfs.handleResponse(0xc20802f680, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:325 +0x102
github.com/github/git-lfs/lfs.doHttpRequest(0xc2080295f0, 0x0, 0x8, 0x79f560)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:246 +0x215
github.com/github/git-lfs/lfs.Download(0xc2080247a0, 0x40, 0x0, 0x0, 0x7f4d3db3a978, 0x2)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:120 +0x1b3
github.com/github/git-lfs/lfs.downloadFile(0x7f4d3dcd9318, 0xc208036008, 0xc2080341c0, 0x7fffb43bb020, 0x13, 0xc208024770, 0x70, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:45 +0x1e8
github.com/github/git-lfs/lfs.PointerSmudge(0x7f4d3dcd9318, 0xc208036008, 0xc2080341c0, 0x7fffb43bb020, 0x13, 0x0, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:31 +0x300
github.com/github/git-lfs/lfs.(*Pointer).Smudge(0xc2080341c0, 0x7f4d3dcd9318, 0xc208036008, 0x7fffb43bb020, 0x13, 0x0, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer.go:44 +0x73
github.com/github/git-lfs/commands.smudgeCommand(0x98d180, 0xc208000b60, 0x1, 0x1)
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_smudge.go:59 +0x819
github.com/spf13/cobra.(*Command).execute(0x98d180, 0xc208000b50, 0x1, 0x1, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x98d780, 0xc20800e010, 0x2, 0x2, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x98d780, 0x0, 0x0)
  /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
  /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
  /Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

**Comment by technoweenie** [comment]
Git LFS [only passes authentication around from the `git-credential` command](https://github.com/github/git-lfs/blob/5e47f06e08e187b8bf74c47efe96d1fa1db17f33/lfs/client.go#L436-L447). I think tweaking it to share Authorization headers from earlier SSH/HTTPS requests is valid, but only if it's to a URL with the same scheme, host, and port.

The git lfs reference server was written without SSH support in mind, so it doesn't add its own authorization headers to the initial Git LFS download request.

**Comment by quinox** [comment]
I'll be looking forward to such a modification in the client code then.

For our testing phase I hacked it into a working state doing the following:
* `git-lfs-authenticate` changes the `href` property to `https://bounce.ytec.nl/git-lfs.php?oid=$oid` in case the second argument of `git-lfs-authenticate` is `download`
*  The bounce server sends `git-lfs` back to the reference server with the right authorization header by running the following PHP code (after appropriate basic auth checks):
```php
<?php  header('Content-Type: application/vnd.git-lfs+json'); ?>
{
  "oid": "<? echo $_GET['oid'] ?>",
  "size": 0,
  "_links": {
    "self": {
      "href": "http://odin.ytec.nl:12345/ytec/lfsrepo/objects/<? echo $_GET['oid'] ?>"
    },
    "download": {
      "href": "http://odin.ytec.nl:12345/ytec/lfsrepo/objects/<? echo $_GET['oid'] ?>",
      "header": {
        "Authorization": "Basic ...encoded-creds...==",
        "Accept": "application/vnd.git-lfs"
      }
    }
  }
}
```

**Comment by bozaro** [comment]
May be related: https://github.com/github/lfs-test-server/pull/32

**Comment by jhoblitt** [comment]
This seems to be working for me with the `v1.0.0` client and `SSH_AUTH_SOCK` set to a gpg-agent socket.  The credential helper gets invoked for the HTTPS auth as expected.  Also note that an API token has to be used with 2FA is enabled.  In that case the username is ignored.
