### ISSUE TITLE
Uploading files to self-hosted git-lfs server works but checkout fails

### ISSUE THREAD

**Issue by lbergelson** [github/git-lfs#287]
I've managed to host my own git-lfs server, and I can check files into it.  I can see them in the management page on the server and my local files are replaced with stubs.

When I clone the repo or try to checkout a commit with large files I can't recover the large files.

I get the following error 
```
 git checkout master
Downloading large.txt (17 B)
Username for 'http://localhost:9999': a
Password for 'http://a@localhost:9999':
Error accessing media: large.txt (1e42ad10d19a2614ecb17185ede8cb12001b1e8b7fb9369d17a01e1413202a82)

Errors logged to /Users/louisb/tmp/newtmp/test-git-lfs/.git/lfs/objects/logs/20150505T114724.17411242.log.
Use `git lfs logs last` to view the log.
Previous HEAD position was e188a3e... adding a regular file
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
```
with this log
```
  test-git-lfs git:(master) git lfs logs last
> git-lfs smudge large.txt
LocalWorkingDir=/Users/louisb/tmp/newtmp/test-git-lfs
LocalGitDir=/Users/louisb/tmp/newtmp/test-git-lfs/.git
LocalMediaDir=/Users/louisb/tmp/newtmp/test-git-lfs/.git/lfs/objects
TempDir=/Users/louisb/tmp/newtmp/test-git-lfs/.git/lfs/tmp
GIT_DIR=.git
GIT_PREFIX=

Error accessing media: large.txt (1e42ad10d19a2614ecb17185ede8cb12001b1e8b7fb9369d17a01e1413202a82)

Error downloading /Users/louisb/tmp/newtmp/test-git-lfs/.git/lfs/objects/1e/42/1e42ad10d19a2614ecb17185ede8cb12001b1e8b7fb9369d17a01e1413202a82.
Authorization error: http://127.0.0.1:9999/user/repo/objects/1e42ad10d19a2614ecb17185ede8cb12001b1e8b7fb9369d17a01e1413202a82
Check that you have proper access to the repository
Request:Content-Length=12
Status=401 Unauthorized
Request:Date=Tue, 05 May 2015 15:47:24 GMT
Request:Content-Type=text/plain; charset=utf-8
Endpoint=http://localhost:9999/user/repo
URL=GET http://127.0.0.1:9999/user/repo/objects/1e42ad10d19a2614ecb17185ede8cb12001b1e8b7fb9369d17a01e1413202a82
Response:User-Agent=git-lfs/0.5.1 (GitHub; darwin amd64; git 2.4.0; go 1.3)
Response:Accept=application/vnd.git-lfs
Request:Www-Authenticate=Basic realm=git-lfs-server
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/lfs.Errorf(0x6581b0, 0xc208001760, 0x3a0fe0, 0x0, 0x0, 0x0, 0x0, 0xb1)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:29 +0x62
github.com/github/git-lfs/lfs.Error(0x6581b0, 0xc208001760, 0xc2080b56b0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:17 +0x52
github.com/github/git-lfs/lfs.defaultError(0xc208048d80, 0x3238e0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:363 +0x151
github.com/github/git-lfs/lfs.handleResponse(0xc208048d80, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:325 +0x102
github.com/github/git-lfs/lfs.doHttpRequest(0xc2080292b0, 0x0, 0x8, 0x3a43a0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:246 +0x215
github.com/github/git-lfs/lfs.Download(0xc20804a9bd, 0x40, 0x0, 0x0, 0x69d978, 0x2)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:120 +0x1b3
github.com/github/git-lfs/lfs.downloadFile(0x65c318, 0xc208036008, 0xc208034380, 0x7fff5fbffbf7, 0x9, 0xc20804a980, 0x7d, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:45 +0x1e8
github.com/github/git-lfs/lfs.PointerSmudge(0x65c318, 0xc208036008, 0xc208034380, 0x7fff5fbffbf7, 0x9, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:31 +0x300
github.com/github/git-lfs/lfs.(*Pointer).Smudge(0xc208034380, 0x65c318, 0xc208036008, 0x7fff5fbffbf7, 0x9, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer.go:44 +0x73
github.com/github/git-lfs/commands.smudgeCommand(0x594100, 0xc208000b60, 0x1, 0x1)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_smudge.go:59 +0x819
github.com/spf13/cobra.(*Command).execute(0x594100, 0xc208000b50, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x594700, 0xc20800e010, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x594700, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

I created an account on the server with username/password a/a, which I could successfully commit files with, but the same account doesn't work to check them back out.  It leaves the repository in a broken state. 

I'm certain that I'm specifying the right username/password when prompted, which worked to upload the files, so I'm not sure why it's not working to download them.

**Comment by rubyist** [comment]
Hi @lbergelson, sorry for the trouble - does the server output any log info?

**Comment by technoweenie** [comment]
If you run `GIT_CURL_VERBOSE=1 git checkout master`, you can see the detailed HTTP requests that Git LFS (and Git) makes.

It looks like the client is sending `Www-Authenticate: Basic realm=git-lfs-server` on the request, and no Authorization header.  I think fixing #243 could help here.

What server are you using?

**Comment by lbergelson** [comment]
Thank you for the help.

Here is the results with a fresh clone.  I recreated the problem with a fresh repo so ignore any changes in hash code from the previous message

```
GIT_CURL_VERBOSE=1 git clone git@github.com:lbergelson/test-git-lfs.git
Cloning into 'test-git-lfs'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 0), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), done.
Checking connectivity... done.
Downloading large (6 B)
Username for 'http://localhost:9999': a
Password for 'http://a@localhost:9999':
> GET /user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1 HTTP/1.1
> User-Agent: git-lfs/0.5.1 (GitHub; darwin amd64; git 2.4.0; go 1.3)
> Authorization: Basic YTph
> Accept: application/vnd.git-lfs+json; charset-utf-8

< HTTP/1.1 200 OK
< Content-Type: application/vnd.git-lfs+json
< Date: Tue, 05 May 2015 17:05:46 GMT
< Content-Length: 268

{"oid":"9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1","size":6,"_links":{"download":{"href":"http://127.0.0.1:9999/user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1","header":{"Accept":"application/vnd.git-lfs"}}}}


* downloaded 268 bytes
> GET /user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1 HTTP/1.1
> Accept: application/vnd.git-lfs
> User-Agent: git-lfs/0.5.1 (GitHub; darwin amd64; git 2.4.0; go 1.3)

< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm=git-lfs-server
< Date: Tue, 05 May 2015 17:05:46 GMT
< Content-Length: 12

Unauthorized
* downloaded 12 bytes
Error accessing media: large (9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1)

Errors logged to /Users/louisb/tmp/clone/test-git-lfs/.git/lfs/objects/logs/20150505T130546.893296564.log.
Use `git lfs logs last` to view the log.
```
client log
```
git lfs logs last
> git-lfs smudge large
LocalWorkingDir=/Users/louisb/tmp/clone/test-git-lfs
LocalGitDir=/Users/louisb/tmp/clone/test-git-lfs/.git
LocalMediaDir=/Users/louisb/tmp/clone/test-git-lfs/.git/lfs/objects
TempDir=/Users/louisb/tmp/clone/test-git-lfs/.git/lfs/tmp
GIT_DIR=.git
GIT_CURL_VERBOSE=1

Error accessing media: large (9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1)

Error downloading /Users/louisb/tmp/clone/test-git-lfs/.git/lfs/objects/9b/fc/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1.
Authorization error: http://127.0.0.1:9999/user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1
Check that you have proper access to the repository
Endpoint=http://localhost:9999/user/repo
Response:User-Agent=git-lfs/0.5.1 (GitHub; darwin amd64; git 2.4.0; go 1.3)
Response:Accept=application/vnd.git-lfs
Request:Www-Authenticate=Basic realm=git-lfs-server
Request:Content-Type=text/plain; charset=utf-8
Request:Content-Length=12
URL=GET http://127.0.0.1:9999/user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1
Status=401 Unauthorized
Request:Date=Tue, 05 May 2015 17:05:46 GMT
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/lfs.Errorf(0x6581b0, 0xc208001970, 0x3a0fe0, 0x0, 0x0, 0x0, 0x0, 0xb1)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:29 +0x62
github.com/github/git-lfs/lfs.Error(0x6581b0, 0xc208001970, 0xc2080b56b0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:17 +0x52
github.com/github/git-lfs/lfs.defaultError(0xc208048ea0, 0x3238e0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:363 +0x151
github.com/github/git-lfs/lfs.handleResponse(0xc208048ea0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:325 +0x102
github.com/github/git-lfs/lfs.doHttpRequest(0xc208029520, 0x0, 0x8, 0x3a43a0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:246 +0x215
github.com/github/git-lfs/lfs.Download(0xc20804a9bc, 0x40, 0x0, 0x0, 0x69d978, 0x2)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:120 +0x1b3
github.com/github/git-lfs/lfs.downloadFile(0x65c318, 0xc208036008, 0xc208034300, 0x7fff5fbffbef, 0x5, 0xc20804a980, 0x7c, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:45 +0x1e8
github.com/github/git-lfs/lfs.PointerSmudge(0x65c318, 0xc208036008, 0xc208034300, 0x7fff5fbffbef, 0x5, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:31 +0x300
github.com/github/git-lfs/lfs.(*Pointer).Smudge(0xc208034300, 0x65c318, 0xc208036008, 0x7fff5fbffbef, 0x5, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer.go:44 +0x73
github.com/github/git-lfs/commands.smudgeCommand(0x594100, 0xc208000b60, 0x1, 0x1)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_smudge.go:59 +0x819
github.com/spf13/cobra.(*Command).execute(0x594100, 0xc208000b50, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x594700, 0xc20800e010, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x594700, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

server output
```
sh run.sh
2015-05-05T17:04:55Z wm1b0-8ab lfs[29491] [proc.go:63]: version=0.2.0 fn=main msg=listening pid=29491 addr=tcp://:9999
2015-05-05T17:05:46Z wm1b0-8ab lfs[29491] [server.go:143]: request_id=80d3491b-7c73-2427-ebc3-d46d336b7783 method=GET url=/user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1 status=200
2015-05-05T17:05:46Z wm1b0-8ab lfs[29491] [server.go:267]: method=GET url=/user/repo/objects/9bfce334a37bd1bc1d36b0370195b31fe9a9389dd43d0873891a3544ef1140a1 status=401 request_id=48e2c814-1a0e-478d-4ea2-8a58ebf6f195
```

I'm using the reference server, running on the same machine.  I'm running it on http instead of https because I had an issue generating an appropriate certificate.

**Comment by lbergelson** [comment]
Here's a screenshot of the management page.  It has the object it's looking for stored in it.
![screen shot 2015-05-05 at 1 11 17 pm](https://cloud.githubusercontent.com/assets/4700332/7478350/42629c8a-f328-11e4-8c5f-abea12eba5e8.png)

**Comment by bozaro** [comment]
Perhaps it is fixed by https://github.com/github/lfs-test-server/pull/32

**Comment by FreakTheMighty** [comment]
I believe I'm seeing this same problem. @lbergelson I fix the issue by adding this to `.git/config`
```
[lfs]
  url = "http://localhost:9999/jesse/lfsrepo"
```
It seems to me that in round tripping from local to remote and back, reference to lfs server is lost.

**Comment by lbergelson** [comment]
This is super out of date now, we're just using the git hub storage since it's available now.  Closing since it's no longer relevant to me.
