### ISSUE TITLE
panic: runtime error uploading files

### ISSUE THREAD

**Issue by tlbtlbtlb** [github/git-lfs#317]
This happened on my first use of git-lfs. I converted about 400 MB of files (by removing and re-adding them) from regular git files to lfs. When I pushed, I got the following panic from the go runtime.

Running git push again completed successfully.

```
lyon ur$ git lfs version
git-lfs/0.5.1 (GitHub; darwin amd64; git 2.2.1; go 1.3)
lyon ur$ uname -a
Darwin lyon.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

lyon ur$ git push
(9 of 31 files) 131.74 MB / 396.45 MB  33.23 % 20m5s                                                                                              Connection to github.com closed by remote host.
(30 of 31 files) 396.45 MB / 396.45 MB  100.00 % 0                                                                                                panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x63bab]

goroutine 31 [running]:
runtime.panic(0x35dfc0, 0x596764)
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/panic.c:279 +0xf5
io/ioutil.devNull.ReadFrom(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/boxen/chgo/versions/1.3/src/pkg/io/ioutil/ioutil.go:151 +0xab
io.Copy(0x65c340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/boxen/chgo/versions/1.3/src/pkg/io/io.go:349 +0x13d
github.com/github/git-lfs/lfs.Upload(0xc208091ab0, 0x65, 0xc20801b3d9, 0x24, 0xc20829bde0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:228 +0xf76
github.com/github/git-lfs/lfs.func·013(0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/upload_queue.go:142 +0x1de
created by github.com/github/git-lfs/lfs.(*UploadQueue).Process
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/upload_queue.go:151 +0x28f

goroutine 16 [semacquire, 30 minutes]:
sync.runtime_Semacquire(0xc20800164c)
	/private/tmp/makerelease410820896/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc208027678)
	/opt/boxen/chgo/versions/1.3/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/github/git-lfs/lfs.(*UploadQueue).Process(0xc208027650)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/upload_queue.go:157 +0x304
github.com/github/git-lfs/commands.prePushCommand(0x594800, 0xc208044640, 0x2, 0x2)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands_pre_push.go:94 +0x49f
github.com/spf13/cobra.(*Command).execute(0x594800, 0xc208044620, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x594700, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x594700, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a

goroutine 19 [finalizer wait]:
runtime.park(0x14260, 0x599d30, 0x598829)
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x599d30, 0x598829)
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1445

goroutine 28 [select]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc208084300)
	/Users/rick/github/git-lfs/.vendor/src/github.com/cheggaaa/pb/pb.go:334 +0xd6
created by github.com/cheggaaa/pb.(*ProgressBar).Start
	/Users/rick/github/git-lfs/.vendor/src/github.com/cheggaaa/pb/pb.go:103 +0x77

goroutine 29 [chan receive, 30 minutes]:
github.com/github/git-lfs/lfs.func·010()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/upload_queue.go:93 +0x60
created by github.com/github/git-lfs/lfs.(*UploadQueue).Process
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/upload_queue.go:96 +0x1bc

goroutine 33 [syscall, 30 minutes]:
runtime.goexit()
	/opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1445
error: failed to push some refs to 'git@github.com:tlbtlbtlb/ur.git'
```

**Comment by technoweenie** [comment]
Thanks for the report.  Looks like a freaky bug in the concurrent uploader due to an HTTP connection error.

**Comment by rubyist** [comment]
Thanks for this report, I think it is a :bug: in the concurrent uploader. I've made some changes in the queues in #285, I'll ensure this is handled there.
