### ISSUE TITLE
git push failing with deleted files

### ISSUE THREAD

**Issue by jonathansick** [github/git-lfs#460]
I tried to push some changes back up to GitHub and got this LFS error log:

```
» git lfs logs last     (preprint) jsick@Helvetica ~/manuscripts/phd_thesis 1 ↵
> git-lfs pre-push origin git@github.com:jonathansick/phd_thesis.git
LocalWorkingDir=/Users/jsick/manuscripts/phd_thesis
LocalGitDir=/Users/jsick/manuscripts/phd_thesis/.git
LocalMediaDir=/Users/jsick/manuscripts/phd_thesis/.git/lfs/objects
TempDir=/Users/jsick/manuscripts/phd_thesis/.git/lfs/tmp
GIT_PREFIX=

Error uploading file figs/resolvedsp/patches/patch_fit_chisq.pdf (a1abaf8316861a74933e5c72de59f4f8e80baa476f17d0505dceea0fec2a69aa)

stat figs/resolvedsp/patches/patch_fit_chisq.pdf: no such file or directory
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/commands.logPanic(0x65daa8, 0xc208025aa0, 0x69da00, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:156 +0xf17
github.com/github/git-lfs/commands.handlePanic(0x65daa8, 0xc208025aa0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:108 +0x6c
github.com/github/git-lfs/commands.LoggedError(0x65daa8, 0xc208025aa0, 0xc208030090, 0x83, 0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:65 +0x89
github.com/github/git-lfs/commands.Panic(0x65daa8, 0xc208025aa0, 0xc208030090, 0x83, 0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:75 +0x68
github.com/github/git-lfs/commands.prePushCommand(0x594800, 0xc208044640, 0x2, 0x2)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands_pre_push.go:84 +0x775
github.com/spf13/cobra.(*Command).execute(0x594800, 0xc208044620, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x594700, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x594700, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
        /Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

The file in question (`figs/resolvedsp/patches/patch_fit_chisq.pdf`) was in the repo but has since been deleted in the current HEAD.

Is there a way I can get this repo back into a shape such that I can push it back up?

**Comment by jonathansick** [comment]
My software versions are:

```
» git lfs version
git-lfs/0.5.1 (GitHub; darwin amd64; git 2.3.5; go 1.3)
» git --version
git version 2.3.5
hub version 1.10.4
```

**Comment by technoweenie** [comment]
Looks like you found a bug in Git LFS where it has issues pushing deleted files. #461 fixes it, and will be available in v0.5.3. Was `figs/resolvedsp/patches/patch_fit_chisq.pdf` added or modified in the range of commits you're trying to push?

Your best bet at a workaround for now is to squash the commits that you're about to push so that you never upload that deleted file. Let me know if you need help. Feel free to join https://gitter.im/github/git-lfs to chat with us directly during normal US work hours next week.

**Comment by jonathansick** [comment]
@technoweenie Thanks for fixing it! I squashed the commits where the file was added then deleted and my `git push` works again.

**Comment by Robinnnnn** [comment]
Would like to bump this issue. 

Getting the exact same error on a second machine where I cloned my repo. After making changes, I cannot push new commits as git lfs tries to upload dozens of files that I had deleted a long time ago.

I've been trying to use [git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch <file/dir>' HEAD](http://stackoverflow.com/questions/19573031/cant-push-to-github-because-of-large-file-which-i-already-deleted) as a temporary fix but quickly gave up when I realized just how many file paths I had to apply this to.

I'm confused as to why files that had been deleted a while back -- _absent both in my local directory and on github_ -- are lingering and providing this error.

Currently using v0.5.4.

```
Error uploading file files/images/project-library/Trash Icon.png (10e7059987de0c34965064ddf0a978c6fac2e0ad2033a7850a4b9a84dcf14e08)

Errors logged to /Users/georgevaldes/Desktop/tollbooth/.git/modules/frontend/lfs/objects/logs/20160308T130535.91275225.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'https://github.com/IrisVR/frontend.git'
Georges-MacBook-Air% git lfs logs last
git-lfs/0.5.4 (GitHub; darwin amd64; go 1.4.2)
git version 2.5.0

$ git-lfs pre-push origin https://github.com/IrisVR/frontend.git
Error uploading file files/images/project-library/Trash Icon.png (10e7059987de0c34965064ddf0a978c6fac2e0ad2033a7850a4b9a84dcf14e08)

Expected files/images/project-library/Trash Icon.png to have an OID of 10e7059987de0c34965064ddf0a978c6fac2e0ad2033a7850a4b9a84dcf14e08, got f4737528fdcf5447670c7b309ecd9c56833e290b5e712865e82b7b23105c9aae
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/lfs/errors.go:85 +0x8d
github.com/github/git-lfs/commands.logPanicToWriter(0x68eb70, 0xc20802a028, 0x68aa00, 0xc2081d8930)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:174 +0xeda
github.com/github/git-lfs/commands.logPanic(0x68aa00, 0xc2081d8930, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:138 +0x414
github.com/github/git-lfs/commands.handlePanic(0x68aa00, 0xc2081d8930, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:113 +0x61
github.com/github/git-lfs/commands.LoggedError(0x68aa00, 0xc2081d8930, 0xc208232000, 0x83, 0x0, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:70 +0x85
github.com/github/git-lfs/commands.Panic(0x68aa00, 0xc2081d8930, 0xc208232000, 0x83, 0x0, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:80 +0x64
github.com/github/git-lfs/commands.prePushCommand(0x5bf5a0, 0xc20801e740, 0x2, 0x2)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/command_pre_push.go:88 +0xa3f
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x5bf5a0, 0xc20801e720, 0x2, 0x2, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x189
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x5bffa0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xd4
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x5bffa0, 0x0, 0x0)
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x8ad
github.com/github/git-lfs/commands.Run()
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/src/github.com/github/git-lfs/commands/commands.go:85 +0x2a
main.main()
    /private/tmp/git-lfs20150803-12429-1wj4067/git-lfs-0.5.4-homebrew/git-lfs.go:9 +0x1b

ENV:
LocalWorkingDir=/Users/georgevaldes/Desktop/tollbooth/frontend
LocalGitDir=/Users/georgevaldes/Desktop/tollbooth/.git/modules/frontend
LocalMediaDir=/Users/georgevaldes/Desktop/tollbooth/.git/modules/frontend/lfs/objects
TempDir=/Users/georgevaldes/Desktop/tollbooth/.git/modules/frontend/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
GIT_DIR=/Users/georgevaldes/Desktop/tollbooth/.git/modules/frontend
GIT_PREFIX=
```

**Comment by technoweenie** [comment]
That error means you dont have `.git/lfs/objects/10/e7/10e7059987de0c34965064ddf0a978c6fac2e0ad2033a7850a4b9a84dcf14e08`. 

What's happening is that it's trying to upload an older version of "files/images/project-library/Trash Icon.png". Since that file above doesn't exist, it tried hashing the actual file. It's failing because apparently that file is different in your HEAD commit.

Try using bfg repo cleaner: https://rtyley.github.io/bfg-repo-cleaner/

Also, that error message has been updated to be more clear (hopefully). I'd highly recommend upgrading, v0.5.4 is ancient :)

**Comment by Robinnnnn** [comment]
Thanks for your advice.

For some reason I'm having a lot of trouble upgrading. `brew install git-lfs` installs 0.5.4 by default. Then typing `brew upgrade git-lfs` gives me `Error: git-lfs 0.5.4 already installed`. How can I get the latest version?

**Comment by technoweenie** [comment]
`brew update` will update the brew recipes. Then you'll have the recipe locally for git lfs v1.1.2.

**Comment by Robinnnnn** [comment]
worked like a charm, thanks for being patiently walking me through!
