### ISSUE TITLE
Error during push

### ISSUE THREAD

**Issue by mnapoli** [github/git-lfs#571]
I committed a file and tried to push to GitHub (worked before) and got an error:

```
$ git push
(1 of 1 files) 483.36 KB 11s
Error for PUT https://github-cloud.s3.amazonaws.com/alambic/media/1548202/ea/d1/ead19505c141c33176836ee7d8ac66d225e1028ce66b8d767b9dff2c116944e3?actor_id=720328

Errors logged to /Users/matthieu/dev/piwik/piwik/.git/lfs/objects/logs/20150810T110831.96858715.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'git@github.com:piwik/piwik.git'
```

Here is the log:

```
> git-lfs pre-push origin git@github.com:piwik/piwik.git
LocalWorkingDir=/Users/matthieu/dev/piwik/piwik
LocalGitDir=/Users/matthieu/dev/piwik/piwik/.git
LocalMediaDir=/Users/matthieu/dev/piwik/piwik/.git/lfs/objects
TempDir=/Users/matthieu/dev/piwik/piwik/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
GIT_PREFIX=

Error for PUT https://github-cloud.s3.amazonaws.com/alambic/media/1548202/ea/d1/ead19505c141c33176836ee7d8ac66d225e1028ce66b8d767b9dff2c116944e3?actor_id=720328

Put https://github-cloud.s3.amazonaws.com/alambic/media/1548202/ea/d1/ead19505c141c33176836ee7d8ac66d225e1028ce66b8d767b9dff2c116944e3?actor_id=720328: EOF
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/lfs/errors.go:85 +0x8d
github.com/github/git-lfs/commands.logPanicToWriter(0x68db70, 0xc20802c0a0, 0x695548, 0xc20826f920)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/commands.go:164 +0x994
github.com/github/git-lfs/commands.logPanic(0x695548, 0xc20826f920, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/commands.go:137 +0x414
github.com/github/git-lfs/commands.handlePanic(0x695548, 0xc20826f920, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/commands.go:112 +0x61
github.com/github/git-lfs/commands.LoggedError(0x695548, 0xc20826f920, 0xc2082c6140, 0xa0, 0x0, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/commands.go:69 +0x85
github.com/github/git-lfs/commands.prePushCommand(0x5be5a0, 0xc20801e820, 0x2, 0x2)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/command_pre_push.go:101 +0x6d5
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x5be5a0, 0xc20801e800, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x189
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x5befa0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xd4
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x5befa0, 0x0, 0x0)
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x8ad
github.com/github/git-lfs/commands.Run()
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/src/github.com/github/git-lfs/commands/commands.go:84 +0x2a
main.main()
        /private/tmp/git-lfs20150727-66675-rv6sh0/git-lfs-0.5.3/git-lfs.go:9 +0x1b
```

```
$ git lfs version
git-lfs/0.5.3 (GitHub; darwin amd64; go 1.4.2)
```

**Comment by mnapoli** [comment]
2nd try yields a different error:

```
$ git push
(1 of 1 files) 175.36 KB 5s
Server error: https://github-cloud.s3.amazonaws.com/alambic/media/1548202/ea/d1/ead19505c141c33176836ee7d8ac66d225e1028ce66b8d767b9dff2c116944e3?actor_id=720328 from HTTP 503
```

3rd try yields another error:

```
$ git push
(1 of 1 files) 541.13 KB 30s
Validation Failed
Docs: https://github.com/contact
```

**Comment by mnapoli** [comment]
Oh well I should have checked that earlier but GitHub seems to have issues: https://status.github.com/ 

Oh and I just tried a 4th time and it worked. I assume it was a GitHub issue :)
