### ISSUE TITLE
Timeout error on Windows in the middle of the upload with KIS [bug]

### ISSUE THREAD

**Issue by MOZGIII** [github/git-lfs#601]
I'm using Git LFS on Windows with Kaspersky Internet Security, which firewalls connection by hooking calls to the OS untill user presses "allow" button in the UI (I guess :D).
So, I think that's why this bug occurs. Now to the bug itself.

Just installed git-lfs, doing my first git push. Had a few KIS UI's telling me about outgoing connection attempt from git-lfs - accepted all of them (maybe after a slight delay).
Upload started, but at file 43/44 git-lfs terminated, with the following error log:

```
git-lfs/0.5.4 (GitHub; windows amd64; go 1.3; git b00fa51)
git version 2.5.0.windows.1

$ git-lfs pre-push origin git@github.com:MOZGIII/Private.git
Error for POST https://api.github.com/lfs/MOZGIII/Private/objects

Post https://api.github.com/lfs/MOZGIII/Private/objects: dial tcp: i/o timeout
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:85 +0x90
github.com/github/git-lfs/commands.logPanicToWriter(0x170320, 0xc08203a110, 0x171eb0, 0xc0820491a0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:174 +0xcb3
github.com/github/git-lfs/commands.logPanic(0x171eb0, 0xc0820491a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:138 +0x38e
github.com/github/git-lfs/commands.handlePanic(0x171eb0, 0xc0820491a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:113 +0x6e
github.com/github/git-lfs/commands.LoggedError(0x171eb0, 0xc0820491a0, 0xc08209c230, 0x41, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:70 +0x90
github.com/github/git-lfs/commands.prePushCommand(0x9d31c0, 0xc082009300, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_pre_push.go:101 +0x655
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x9d31c0, 0xc0820092e0, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x183
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x9d3bc0, 0xc082004450, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xda
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x9d3bc0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x7b7
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x31
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x21

ENV:
LocalWorkingDir=R:\dev\Private
LocalGitDir=R:\dev\Private\.git
LocalMediaDir=R:\dev\Private\.git\lfs\objects
TempDir=R:\dev\Private\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=false
GIT_PREFIX=
```

Seems like antivirus interferes with connection attemts, leading git-lfs to think connections were unsuccessfull, however when thay are actually connected, it messes with the timeouted old ones, leading to panic (or whatever that crash was).

**Comment by technoweenie** [comment]
This is a pretty normal timeout error. Can you put git lfs into a whitelist so it's not being blocked by the firewall?

**Comment by MOZGIII** [comment]
Yes, I already fixed it on my setup. Just reporting this strange behaviour.
The weird part is that after it connected and started uploading files (successfully), a timeout occured in the middle of the work.
I don't know if it can be fixed in the app itself or even should be treated as bug though.

**Comment by technoweenie** [comment]
@MOZGIII I'm going to ignore this for now. IMO the [current 5s connection timeout](https://github.com/github/git-lfs/blob/3f1eec26a25b0c8e17f8b89c3d3dd419189d80c5/lfs/http.go#L108-L112) is plenty (it does not count the time to upload or download files). This shouldn't be a problem after you've whitelisted Git LFS.

It would be cool if we could white list Git LFS during installation or something though.

**Comment by MOZGIII** [comment]
Yeah, I guess it's ok.
Adding `git-lfs` to the ignore list would really be great, but it's an AV software and I'm pretty sure it can't be done manually.
It's not a big problem at all though.

**Comment by bitcruncher** [comment]
yes it is a very big problem, because I cannot use git LFS period. 5mb or 5gb it continuously fails.

**Comment by larsxschneider** [comment]
I ran into the same issue (see log below /cc @mgriffin).

@technoweenie Would it make sense to add a Git LFS config for the timeout?

```
git lfs logs last
git-lfs/1.1.0 (GitHub; windows amd64; go 1.5.1; git 258acf1)
git version 2.7.0.windows.1

$ git-lfs.exe smudge redacted.bin
Error accessing media: redacted.bin (097d57244ca0da8dbaa4d9000386465543921af304f94f1ae0450c5fafc3314c)

Post https://redacted-server.com/org/repo.git/info/lfs/objects/batch: dial tcp 11.22.33.44:443: i/o timeout
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0xf241e8, 0xc082166028, 0x3101498, 0xc082152490)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf86
github.com/github/git-lfs/commands.logPanic(0x3101498, 0xc082152490, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x428
github.com/github/git-lfs/commands.handlePanic(0x3101498, 0xc082152490, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x55
github.com/github/git-lfs/commands.LoggedError(0x3101498, 0xc082152490, 0x967a80, 0x1e, 0xc08209bc78, 0x2, 0x2)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x89
github.com/github/git-lfs/commands.smudgeCommand(0xb69f60, 0xc082007a20, 0x1, 0x1)
/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd90
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb69f60, 0xc082007970, 0x1, 0x1, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x40a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb6afa0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x59a
github.com/github/git-lfs/commands.Run()
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x2a
main.main()
/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git\lfs\objects
TempDir=.git\lfs\tmp
ConcurrentTransfers=10
BatchTransfer=true
GIT_ASKPASS=echo
GIT_BRANCH=origin/master
GIT_COMMIT=1f84fe47c5aa08082c33eda430bbf246ddaf93ed
GIT_DIR=.git
GIT_PREFIX=
GIT_PREVIOUS_COMMIT=1f84fe47c5aa08082c33eda430bbf246ddaf93ed
GIT_PREVIOUS_SUCCESSFUL_COMMIT=1f84fe47c5aa08082c33eda430bbf246ddaf93ed
GIT_URL=https://redacted-server.com/org/repo.git
GIT_WORK_TREE=.
```

**Comment by technoweenie** [comment]
Yeah, I've been meaning to do that, actually. #977

**Comment by MOZGIII** [comment]
Nice +1
