### ISSUE TITLE
Push not possible because of EOF

### ISSUE THREAD

**Issue by ManuelGysin** [github/git-lfs#602]
Hello

Since three days I'm trying to push a migrated repo but everytime it's ending with:

```
git lfs logs last
git-lfs/0.5.4 (GitHub; linux amd64; go 1.3; git b00fa51)
git version 2.4.3

$ git-lfs push origin master
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Post https://api.github.com/lfs/QuantumBytesInc/ROAC/objects: EOF
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/commands.logPanicToWriter(0x7fafba728318, 0xc209984d08, 0x7fafba43d2a8, 0xc208cb3a70)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:174 +0xcac
github.com/github/git-lfs/commands.logPanic(0x7fafba43d2a8, 0xc208cb3a70, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:138 +0x387
github.com/github/git-lfs/commands.handlePanic(0x7fafba43d2a8, 0xc208cb3a70, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:113 +0x67
github.com/github/git-lfs/commands.LoggedError(0x7fafba43d2a8, 0xc208cb3a70, 0xc2090f5630, 0x46, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:70 +0x89
github.com/github/git-lfs/commands.pushCommand(0x9b13e0, 0xc208046840, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_push.go:166 +0x48e
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x9b13e0, 0xc208046820, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x17c
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x9b1ce0, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xd3
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x9b1ce0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x2a
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x1a

ENV:
LocalWorkingDir=/home/mgysin/Projects/migration/ROAC_testing
LocalGitDir=/home/mgysin/Projects/migration/ROAC_testing/.git
LocalMediaDir=/home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects
TempDir=/home/mgysin/Projects/migration/ROAC_testing/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
```

Each run takes hours and the output looks like (output after some hours):

```
 git lfs push origin master
(1 of 15982 files) 101.00 MB 3h27m14s                                                                                                                                                                              
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.789433194.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.798508443.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.801717088.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.805759988.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.809031325.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.811221387.log
Use `git lfs logs last` to view the log.
Error for POST https://api.github.com/lfs/QuantumBytesInc/ROAC/objects

Errors logged to /home/mgysin/Projects/migration/ROAC_testing/.git/lfs/objects/logs/20150822T195326.812847581.log
Use `git lfs logs last` to view the log.
git lfs push origin master  121.57s user 67.24s system 1% cpu 3:27:17.96 total
```

Greets
Manuel

**Comment by bozaro** [comment]
I'm a little surprised.

If I understand correctly, you trying to use utility https://github.com/bozaro/git-lfs-migrate for repository migrating.

This utility converts repository by steps like:

 * Pull repository: ```git clone --mirror git@github.com:bozaro/git-lfs-migrate.git```
 * Convert repository and upload LFS object to GitHub: ```java -jar git-lfs-migrate.jar -s git-lfs-migrate.git -d git-lfs-migrate-converted.git -l https://bozaro:*****@api.github.com/lfs/bozaro/git-lfs-migrate-converted .jar```
 * Push converted repository: cd git-lfs-migrate-converted.git && git fsck && git push --mirror git@github.com:bozaro/git-lfs-migrate-converted.git

In this use case ```git lfs``` utility is not used and this error can't occur.

I do not understand how to get the repository, which led to this error.

**Comment by ManuelGysin** [comment]
Hello,

You are right, my mistake was that I precloned the target repository and that caused LFS to run.
After running git-lfs-migrate in an empty folder, LFS was not invoked.

At general the LFS errors could be avoided after switching to HTTPS instead of SSH.
