### ISSUE TITLE
go panic on committing

### ISSUE THREAD

**Issue by pokehanai** [github/git-lfs#880]
Hi,

It was first time to use git-lfs and the very first experiment was not so good. :weary:
On the first commit I faced the following panic stacktrace.

```
panic: runtime error: makeslice: len out of range

goroutine 68 [running]:
strings.Repeat(0x4fced0, 0x1, 0xffffffffffffffd9, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/strings/strings.go:464 +0x5f
github.com/github/git-lfs/lfs.(*ProgressMeter).update(0xc820264000)
    /Users/rick/go/src/github.com/github/git-lfs/lfs/progress_meter.go:140 +0x7c1
github.com/github/git-lfs/lfs.(*ProgressMeter).writer(0xc820264000)
    /Users/rick/go/src/github.com/github/git-lfs/lfs/progress_meter.go:106 +0x30
created by github.com/github/git-lfs/lfs.(*ProgressMeter).Start
    /Users/rick/go/src/github.com/github/git-lfs/lfs/progress_meter.go:57 +0x60
```

Then I checked the code and the cause.
```go
// around lfs/progress_meter.go:140
func (p *ProgressMeter) update() {
	if p.dryRun || p.estimatedFiles == 0 {
		return
	}

	width := 80 // default to 80 chars wide if ts.GetSize() fails
	size, err := ts.GetSize()
	if err == nil {
		width = size.Col()
	}

	// (%d of %d files, %d skipped) %f B / %f B, %f B skipped
	// skipped counts only show when > 0

	out := fmt.Sprintf("\rGit LFS: (%d of %d files", p.finishedFiles, p.estimatedFiles)
	if p.skippedFiles > 0 {
		out += fmt.Sprintf(", %d skipped", p.skippedFiles)
	}
	out += fmt.Sprintf(") %s / %s", formatBytes(p.currentBytes), formatBytes(p.estimatedBytes))
	if p.skippedBytes > 0 {
		out += fmt.Sprintf(", %s skipped", formatBytes(p.skippedBytes))
	}

	padding := strings.Repeat(" ", width-len(out))
	fmt.Fprintf(os.Stdout, out+padding)
}
```

In my case, at the secondary last line `width-len(out)` was `-39`; enough to cause Go panic.
By tweaking like
```go
    padlen := width - len(out)
    if 0 < padlen {
        padding := strings.Repeat(" ", padlen)
        out += padding
    }
    fmt.Fprintf(os.Stdout, out)
```
then my first commit had been finished successfully.

I am not sure why `width` was `0`.
I use Emacs+magit or Emacs+shell on Mac.
Maybe `ts.GetSize()` needs to be improved. But still it is good to have guard code like above.

Anyway, thanks for providing `git-lfs`. I think I will love the tool a lot.:smiley:

**Comment by technoweenie** [comment]
@pokehanai Thanks for the report. I'm guessing [the ts package](https://github.com/olekukonko/ts) is unable detect the terminal size from inside emacs.

I made a PR with your patch: #883. Is there a reason you didn't file it yourself as a pull request?

**Comment by pokehanai** [comment]
Ah, I have other tasks to do today; then I thought that I did not have enough time to *develop* test code against it.
And rather it would be worth to let the community know the issue and fixing code, so I just reported.

**Comment by cschroed-usgs** [comment]
I reproduced a very similar issue with git lfs 1.1.0 while running the `fetch` and `checkout` lfs commands in a Travis build environment (Ubuntu precise pangolin). The progress bar is unable to detect the width of Travis' terminal. You can work around the issue by piping the git lfs commands to /dev/null if you don't care about the output, or by piping to files and `cat`ing the files afterwards if you want to inspect the output.

[This travis configuration](https://github.com/cschroed-usgs/jaguaR/blob/ce6962f6ec2ed0a731ec4cf024b5b8e9a12e8bd8/.travis.yml)
```
language: r
sudo: required
before_script:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs=1.1.0
  - git lfs fetch
  - git lfs checkout
```
produces [this error output](https://travis-ci.org/cschroed-usgs/jaguaR/builds/97103015#L1645)
```
21.25s$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
Detected operating system as Ubuntu/precise.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.
The repository is setup! You can now install packages.
before_script.2
4.60s$ sudo apt-get install git-lfs=1.1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  git-lfs
0 upgraded, 1 newly installed, 0 to remove and 56 not upgraded.
Need to get 2,287 kB of archives.
After this operation, 11.2 MB of additional disk space will be used.
Get:1 https://packagecloud.io/github/git-lfs/ubuntu/ precise/main git-lfs amd64 1.1.0 [2,287 kB]
Fetched 2,287 kB in 1s (1,248 kB/s)
Selecting previously unselected package git-lfs.
(Reading database ... 165111 files and directories currently installed.)
Unpacking git-lfs (from .../git-lfs_1.1.0_amd64.deb) ...
Processing triggers for man-db ...
Setting up git-lfs (1.1.0) ...
0.61s$ git lfs fetch
Fetching HEAD
Git LFS: (0 of 1 files) 0 B / 9.18 MB  panic: runtime error: makeslice: len out of range
goroutine 51 [running]:
strings.Repeat(0x8ff5f0, 0x1, 0xfffffffffffffffc, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:464 +0x5f
github.com/github/git-lfs/lfs.(*ProgressMeter).update(0xc8200e2000)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:140 +0x7c1
github.com/github/git-lfs/lfs.(*ProgressMeter).writer(0xc8200e2000)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:112 +0xf6
created by github.com/github/git-lfs/lfs.(*ProgressMeter).Start
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:57 +0x60
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8200ee19c)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8200ee190)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/github/git-lfs/lfs.(*TransferQueue).Wait(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:86 +0x75
github.com/github/git-lfs/commands.fetchAndReportToChan(0xc8200dc010, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_fetch.go:302 +0x54c
github.com/github/git-lfs/commands.fetchPointers(0xc8200dc010, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8200cd2f0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_fetch.go:239 +0x8d
github.com/github/git-lfs/commands.fetchRef(0xc820013830, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_fetch.go:136 +0x111
github.com/github/git-lfs/commands.fetchCommand(0xb58640, 0xb83e98, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_fetch.go:80 +0x781
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb58640, 0xb83e98, 0x0, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb5b220, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
goroutine 28 [chan receive]:
github.com/github/git-lfs/lfs.(*TransferQueue).retryCollector(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:263 +0x58
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:318 +0x64
goroutine 19 [select, locked to thread]:
runtime.gopark(0x9d2928, 0xc820026728, 0x904a88, 0x6, 0x42c618, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
goroutine 20 [chan receive]:
main.main.func1(0xc8200e6ba0, 0xc8200ccae0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/git-lfs.go:22 +0x6d
created by main.main
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/git-lfs.go:32 +0x129
goroutine 27 [chan receive]:
github.com/github/git-lfs/lfs.(*TransferQueue).errorCollector(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:256 +0x5b
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:317 +0x3f
goroutine 29 [IO wait]:
net.runtime_pollWait(0x7faa3ecb0418, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820168060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820168060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820168000, 0xc82019ecf0, 0x7310, 0x7310, 0x0, 0x7faa412fa050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002e000, 0xc82019ecf0, 0x7310, 0x7310, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203c6390, 0x7faa41300a98, 0xc82002e000, 0x4035, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200be2c0, 0x9d2917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:583 +0xccf
crypto/tls.(*Conn).Read(0xc8200be2c0, 0xc82018e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7faa41309b88, 0xc8200be2c0, 0xc8204470d8, 0xc82018e000, 0x8000, 0x8000, 0x400, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8200cbd80, 0xc82018e000, 0x8000, 0x8000, 0xc820030d80, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).Read(0xc820360d20, 0xc82018e000, 0x8000, 0x8000, 0xc820030d80, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:197 +0x126
io.(*LimitedReader).Read(0xc8200cbe20, 0xc82018e000, 0x8000, 0x8000, 0xc82004b5b0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
net/http.(*body).readLocked(0xc820158900, 0xc82018e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc820158900, 0xc82018e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc820158940, 0xc82018e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1296 +0x26a
github.com/github/git-lfs/lfs.(*countingReadCloser).Read(0xc8203c77a0, 0xc82018e000, 0x8000, 0x8000, 0xc82004b810, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/http.go:240 +0x9e
github.com/github/git-lfs/lfs.(*hashingReader).Read(0xc8200cbea0, 0xc82018e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/pointer_smudge.go:304 +0x85
github.com/github/git-lfs/lfs.(*CallbackReader).Read(0xc8203c7800, 0xc82018e000, 0x8000, 0x8000, 0x400, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/util.go:34 +0x75
io.copyBuffer(0x7faa412fe1e8, 0xc82002e048, 0x7faa3ecb0c00, 0xc8203c7800, 0xc82018e000, 0x8000, 0x8000, 0x26289, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7faa412fe1e8, 0xc82002e048, 0x7faa3ecb0c00, 0xc8203c7800, 0x40c69d, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
github.com/github/git-lfs/lfs.CopyWithCallback(0x7faa412fe1e8, 0xc82002e048, 0x7faa3ecb0bd8, 0xc8200cbea0, 0x92e670, 0xc8202bae60, 0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/util.go:57 +0x143
github.com/github/git-lfs/lfs.bufferDownloadedFile(0xc8200ff100, 0x7f, 0x7faa41309c50, 0xc8203c77a0, 0x92e670, 0xc8202bae60, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/pointer_smudge.go:175 +0x39b
github.com/github/git-lfs/lfs.downloadObject(0xc8200165a0, 0xc8203eb980, 0xc8200ff100, 0x7f, 0xc8202bae60, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/pointer_smudge.go:113 +0x2bb
github.com/github/git-lfs/lfs.PointerSmudgeObject(0xc8200165a0, 0xc8203eb980, 0xc8202bae60, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/pointer_smudge.go:89 +0x1a0
github.com/github/git-lfs/lfs.(*Downloadable).Transfer(0xc8200dc018, 0xc8202bae60, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/download_queue.go:61 +0x51
github.com/github/git-lfs/lfs.(*TransferQueue).transferWorker(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:276 +0x159
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:322 +0x167
goroutine 30 [chan receive]:
github.com/github/git-lfs/lfs.(*TransferQueue).transferWorker(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:270 +0x98
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:322 +0x167
goroutine 31 [chan receive]:
github.com/github/git-lfs/lfs.(*TransferQueue).transferWorker(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:270 +0x98
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:322 +0x167
goroutine 33 [chan receive]:
github.com/github/git-lfs/lfs.(*TransferQueue).batchApiRoutine(0xc8200ee0d0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:193 +0xd7
created by github.com/github/git-lfs/lfs.(*TransferQueue).run
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/transfer_queue.go:328 +0x2b7
goroutine 16 [IO wait]:
net.runtime_pollWait(0x7faa3ecb0598, 0x72, 0xc820014200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82005a680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82005a680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82005a620, 0xc8200df000, 0x1000, 0x1000, 0x0, 0x7faa412fa050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002e020, 0xc8200df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82010c240, 0x7faa41300a98, 0xc82002e020, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200be000, 0x9d2917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200be000, 0xc820021000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7faa41309b88, 0xc8200be000, 0xc820446478, 0xc820021000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202ba780, 0xc820021000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001bc20)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001bc20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820446420)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 50 [select]:
net/http.(*persistConn).writeLoop(0xc820446420)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 39 [select]:
net/http.(*persistConn).readLoop(0xc820447080)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc820447080)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
The command "git lfs fetch" failed and exited with 2 during .
Your build has been stopped.
```

[Here is an example Travis configuration](https://github.com/cschroed-usgs/jaguaR/blob/dccf103f626931daa273c2745b6513bdd56d2df2/.travis.ymlhttps://github.com/cschroed-usgs/jaguaR/blob/dccf103f626931daa273c2745b6513bdd56d2df2/.travis.yml) using the pipe-based workaround:
```
language: r
sudo: required
before_script:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs=1.1.0
# On travis using git-lfs 1.1.0, must prevent git lfs from writing directly to stdout.
# This is a known bug for which a fix has been merged into upstream.
# see: https://github.com/github/git-lfs/issues/880
  - git lfs fetch > /tmp/git-lfs-fetch.log
  - cat /tmp/git-lfs-fetch.log
  - git lfs checkout > /tmp/git-lfs-checkout.log
  - cat /tmp/git-lfs-checkout.log
```

And here is [the output for the workaround](https://travis-ci.org/cschroed-usgs/jaguaR/builds/97249506#L1646):
```
$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
Detected operating system as Ubuntu/precise.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.
The repository is setup! You can now install packages.
before_script.2
4.63s$ sudo apt-get install git-lfs=1.1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  git-lfs
0 upgraded, 1 newly installed, 0 to remove and 56 not upgraded.
Need to get 2,287 kB of archives.
After this operation, 11.2 MB of additional disk space will be used.
Get:1 https://packagecloud.io/github/git-lfs/ubuntu/ precise/main git-lfs amd64 1.1.0 [2,287 kB]
Fetched 2,287 kB in 1s (1,247 kB/s)
Selecting previously unselected package git-lfs.
(Reading database ... 165111 files and directories currently installed.)
Unpacking git-lfs (from .../git-lfs_1.1.0_amd64.deb) ...
Processing triggers for man-db ...
Setting up git-lfs (1.1.0) ...
before_script.3
2.36s$ git lfs fetch > /tmp/git-lfs-fetch.log
before_script.4
0.00s$ cat /tmp/git-lfs-fetch.log
Fetching HEAD
Git LFS: (1 of 1 files) 9.17 MB / 9.18 MB                                      
before_script.5
0.21s$ git lfs checkout > /tmp/git-lfs-checkout.log
before_script.6
0.00s$ cat /tmp/git-lfs-checkout.log
Git LFS: (1 of 1 files) 9.18 MB / 9.18 MB                                      
```

**Comment by freemancw** [comment]
Experiencing this as well on 1.1.0.

**Comment by technoweenie** [comment]
Should be fixed in #883. Thanks for the workaround, @cschroed-usgs:

> You can work around the issue by piping the git lfs commands to `/dev/null` if you don't care about the output, or by piping to files and cating the files afterwards if you want to inspect the output.

**Comment by cschroed-usgs** [comment]
:+1: de nada

**Comment by k06a** [comment]
Just found nice piping workaround:
```
- git lfs fetch | cat
- git lfs checkout | cat
```

**Comment by cschroed-usgs** [comment]
@k06a that's elegant. Nice!

**Comment by cschroed-usgs** [comment]
Echoing his call for a release that incorporates the fix. :shipit:

**Comment by msc-** [comment]
+1 to call for release that incorporates the fix. I too am suffering. In my case on both Trusty (Ubuntu 14.04) and OS X on travis-ci.
