### ISSUE TITLE
Not working in directory that is a symbolic link to another directory

### ISSUE THREAD

**Issue by cpaulik** [github/git-lfs#896]
I've setup my `~/workspace` to link to another folder for convenience.

However I get the following error when cloning and pulling a git lfs directory.

Switching to the actual folder and running `git lfs pull` works.

```shell
cpa@cpa:~/workspace$ git clone https://git.geo.tuwien.ac.at/cpaulik/git-lfs-test.git
Cloning into 'git-lfs-test'...
Username for 'https://git.geo.tuwien.ac.at': cpaulik
Password for 'https://cpaulik@git.geo.tuwien.ac.at': 
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
cpa@cpa:~/workspace$ cd git-lfs-test/
cpa@cpa:~/workspace/git-lfs-test$ git lfs pull
Username for 'https://git.geo.tuwien.ac.at': cpaulik
Password for 'https://cpaulik@git.geo.tuwien.ac.at': 
Git LFS: (1 of 1 files) 1.52 MB / 1.52 MB                                                                      
Error updating the git index


Errors logged to /home/cpa/workspace/git-lfs-test/.git/lfs/objects/logs/20151215T124713.693446697.log
Use `git lfs logs last` to view the log.
cpa@cpa:~/workspace/git-lfs-test$ git lfs logs last
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1)
git version 2.6.4

$ git-lfs pull
Error updating the git index


exit status 128
goroutine 46 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f463c9361e8, 0xc820204118, 0x7f4638295a50, 0xc820204110)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f4638295a50, 0xc820204110, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f4638295a50, 0xc820204110, 0x0, 0x0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f4638295a50, 0xc820204110, 0x95d480, 0x1f, 0xc820055e80, 0x1, 0x1)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.checkoutWithChan(0xc820138900)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:229 +0xa5c
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc820138900, 0xc82011d8c0)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x21
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x439

ENV:
LocalWorkingDir=/data/Development/python/workspace/git-lfs-test
LocalGitDir=/home/cpa/workspace/git-lfs-test/.git
LocalGitStorageDir=/home/cpa/workspace/git-lfs-test/.git
LocalMediaDir=/home/cpa/workspace/git-lfs-test/.git/lfs/objects
TempDir=/home/cpa/workspace/git-lfs-test/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
```

**Comment by gurugray** [comment]
#866

**Comment by technoweenie** [comment]
Hi, I'm replying to old issues that I've missed. As @gurugray mentioned, this looks like a dup of #866.

**Comment by gurugray** [comment]
yep, looks like duplicate
