### ISSUE TITLE
Cloning a new repo from 0, error "smudge filter lfs failed"

### ISSUE THREAD

**Issue by antero10** [github/git-lfs#926]
I was cloning a repo from 0, and then i get this error

 smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

i have this on the log

```
git-lfs/1.0.1 (GitHub; darwin amd64; go 1.5.1)
git version 2.5.4 (Apple Git-61)

$ git-lfs smudge assets/caffe_model/20001/caffenet_train_20001.caffemodel
Error accessing media: assets/caffe_model/20001/caffenet_train_20001.caffemodel (3aa57f2061290d60381a063b5d9edaca8269984b592a2b2fec9c20e925cae6fe)

relation does not exist
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0xc641e8, 0xc8205f2000, 0xc64e90, 0xc8200e6c20)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0xc64e90, 0xc8200e6c20, 0x0, 0x0)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0xc64e90, 0xc8200e6c20, 0x0, 0x0)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xc64e90, 0xc8200e6c20, 0x4e2900, 0x1e, 0xc820605ca8, 0x2, 0x2)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x6baf20, 0xc820011930, 0x1, 0x1)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/command_smudge.go:80 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x6baf20, 0xc820011880, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x6bbc20, 0x0, 0x0)
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/private/tmp/git-lfs20151027-97833-bhsob1/git-lfs-1.0.1/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
GIT_WORK_TREE=.
```

i don't know what happen or how i can  resolve this error.

**Comment by technoweenie** [comment]
> relation does not exist

That looks like the object `3aa57f2061290d60381a063b5d9edaca8269984b592a2b2fec9c20e925cae6fe` is not on your LFS server. If you're using GitHub, send me more details at https://github.com/contact, and I can help you out.

**Comment by technoweenie** [comment]
Closing this. Re-open if you have any other questions.
