### ISSUE TITLE
git lfs fetch fails when repo is owned by another user but is group-writable

### ISSUE THREAD

**Issue by parejkoj** [github/git-lfs#943]
We have a git lfs repo that could be updated by multiple people. However, when someone who is not the owner of the files in the repo tries `git lfs pull` when there are files to update, the repository gets into a broken state where noone can do the pull until the offending files are deleted and the pull is done by the owner.

To be clear, the directory has the GUID bit set, and all subdirectories have g+w permissions, and both users are in the group that the files belong to.

Steps to reproduce:
1. Checkout a repository as one user, with g+w permissions throughout and a group that another user belongs to.
2. Delete a file.
3. Run `git lfs pull` as a different user in the group. Receive "Could not checkout file" error, but a 0-length file will have been created.
4. Run `git lfs pull` as the directory owner. Receive "Problem accessing FILENAME" error.
5. Delete the 0-length file.
6. Run `git lfs pull` as the directory owner. The file will be pulled correctly.

I will attach some logs to help demonstrate the details.

**Comment by parejkoj** [comment]
The state of our test file before being deleted:
```
$ l CFHT/D2/
total 4548
drwxrwsr-x 2 parejkoj astro-apps6      40 Jan 21 14:43 .
drwxrwsr-x 4 parejkoj astro-apps6      24 Jan 21 13:49 ..
-rw-rw-r-- 1 parejkoj astro-apps6  113341 Jan 21 14:43 sdss.dat
-rw-rw-r-- 1 parejkoj astro-apps6 4458056 Jan 21 14:40 template.dat
```
We delete the file:

```
$ rm CFHT/D2/sdss.dat
$ l CFHT/D2/
total 4
drwxrwsr-x 2 parejkoj astro-apps6  25 Jan 21 14:39 .
drwxrwsr-x 4 parejkoj astro-apps6  24 Jan 21 13:49 ..
-rw-rw-r-- 1 parejkoj astro-apps6 132 Jan 21 13:49 template.dat
```

Another user runs git lfs pull, and receives the following error:

```
$ git-lfs pull
Could not checkout file

open /astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/objects/logs/20160121T144502.352056015.log: permission denied
goroutine 113 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
  /Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f3870a331e8, 0xc820054018, 0x7f3870a335b8, 0xc8200f22a0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic.func1(0xc8208dfba0, 0xc820165380, 0x60, 0x7f3870a335b8, 0xc8200f22a0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:141 +0x157
github.com/github/git-lfs/commands.logPanic(0x7f3870a2f028, 0xc8200f8080, 0x0, 0x0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:150 +0x43c
github.com/github/git-lfs/commands.handlePanic(0x7f3870a2f028, 0xc8200f8080, 0x0, 0x0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f3870a2f028, 0xc8200f8080, 0x8d1860, 0x17, 0x0, 0x0, 0x0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.checkoutWithChan(0xc8200155c0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:202 +0x860
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc8200155c0, 0xc8200122f0)
  /Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x21
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
  /Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x439

ENV:
LocalWorkingDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj
LocalGitDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git
LocalGitStorageDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git
LocalMediaDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/objects
TempDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
(0 of 174 files) 0 B / 3.15 GB
```

**Comment by parejkoj** [comment]
After the above, a 0-length file has been created, owned by the other user:
```
parejkoj$ l CFHT/D2/
total 4356
drwxrwsr-x 2 parejkoj astro-apps6      40 Jan 21 14:42 .
drwxrwsr-x 4 parejkoj astro-apps6      24 Jan 21 13:49 ..
-rw-rw-r-- 1 rowen    astro-apps6       0 Jan 21 14:42 sdss.dat
-rw-rw-r-- 1 parejkoj astro-apps6 4458056 Jan 21 14:40 template.dat
```

If the original repo owner tries to pull, they receive a different error, which specifically refers to the file this time:

```
parejkoj$ git lfs pull
Problem accessing CFHT/D2/sdss.dat

Errors logged to /astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/objects/logs/20160121T144323.228011914.log
Use `git lfs logs last` to view the log.
(0 of 174 files) 0 B / 3.15 GB


parejkoj$ git lfs logs last
git-lfs/1.0.2 (GitHub; linux amd64; go 1.5.1; git 0566698)
git version 2.2.2

$ git-lfs pull
Problem accessing CFHT/D2/sdss.dat

EOF
goroutine 102 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f05f7f1e1e8, 0xc8201d0058, 0x7f05f7f1a028, 0xc820012160)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f05f7f1a028, 0xc820012160, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f05f7f1a028, 0xc820012160, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f05f7f1a028, 0xc820012160, 0x8d2980, 0x14, 0xc8202ffed0, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.checkoutWithChan(0xc8201796e0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:183 +0x2fd
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc8201796e0, 0xc820012450)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x21
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x439

ENV:
LocalWorkingDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj
LocalGitDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git
LocalGitStorageDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git
LocalMediaDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/objects
TempDir=/astro/apps6/opt/lsstStacks/afwdata-parejkoj/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
```

**Comment by parejkoj** [comment]
Finally, we delete that 0-length file, and try the `git lfs pull` as the original user, and it works:

```
parejkoj$ rm CFHT/D2/sdss.dat
parejkoj$ git lfs pull
(0 of 174 files) 0 B / 3.15 GB
parejkoj$ l CFHT/D2/
total 4548
drwxrwsr-x 2 parejkoj astro-apps6      40 Jan 21 14:43 .
drwxrwsr-x 4 parejkoj astro-apps6      24 Jan 21 13:49 ..
-rw-rw-r-- 1 parejkoj astro-apps6  113341 Jan 21 14:43 sdss.dat
-rw-rw-r-- 1 parejkoj astro-apps6 4458056 Jan 21 14:40 template.dat
```

**Comment by technoweenie** [comment]
Hi, I'm going through and replying to old issues that I've missed.

> After the above, a 0-length file has been created, owned by the other user:

```
parejkoj$ l CFHT/D2/
total 4356
drwxrwsr-x 2 parejkoj astro-apps6      40 Jan 21 14:42 .
drwxrwsr-x 4 parejkoj astro-apps6      24 Jan 21 13:49 ..
-rw-rw-r-- 1 rowen    astro-apps6       0 Jan 21 14:42 sdss.dat
-rw-rw-r-- 1 parejkoj astro-apps6 4458056 Jan 21 14:40 template.dat
```

This looks like it's associated with the correct user and group. How would you expect Git LFS to fix this?

**Comment by r-owen** [comment]
Have you tried reproducing the bug? It's not that the visible files get pulled over in a surprising way, it's that the repository is badly broken afterwards. No further pulls can be made afterwards. It is as if some invisible file has the wrong permission, or the system is trying to access the visible files using the wrong credentials.

**Comment by technoweenie** [comment]
Nope, haven't had time, unfortunately. I've labeled this as `bug`, until someone has time to look at it in more detail. Thanks for the report!

**Comment by javabrett** [comment]
Looks like it croaked attempting to write logging to `lfs/objects/logs/...`.  I know you say you have SGID set for all subdirs, but can you reconfirm for this directory?

It is possible that the sub-dirs under `logs` are not inheriting SGID.  What is your filesystem type, and is it mounted with any interesting options like `-o grpid` or `-o nogrpid`?

**Comment by r-owen** [comment]
The SGID bit does appear to be set, as per the following (I checked all directories in this tree):

    ls -ld .git/lfs/objects/logs
    drwxr-sr-x 2 parejkoj astro-apps6 42 Jan 21 14:43 .git/lfs/objects/logs

The filesystem type is `nfs` and the `mount` command lists the following options: `rw,rsize=8192,wsize=8192,vers=3,sloppy,addr=...`

**Comment by r-owen** [comment]
I see. It is the fact that group is unwritable. Here's a more complete listing which shows that `.git/` is fine, but `.git/lfs` and its subdirectories are not, as if git-lfs is ignoring our umask when creating the directories and files in `.git/`:
```
astrolab18$ ls -ld .git/
drwxrwsr-x 9 parejkoj astro-apps6 4096 Mar  4 16:31 .git/

astrolab18$ ls -ld .git/lfs/
drwxr-sr-x 4 parejkoj astro-apps6 30 Jan 21 13:49 .git/lfs/

astrolab18$ ls -ld .git/lfs/objects/
drwxr-sr-x 148 parejkoj astro-apps6 4096 Jan 21 14:40 .git/lfs/objects/

astrolab18$ ls -ld .git/lfs/objects/logs
drwxr-sr-x 2 parejkoj astro-apps6 42 Jan 21 14:43 .git/lfs/objects/logs

astrolab18$ umask
0002
```

**Comment by javabrett** [comment]
* You don't mention the filesystem type behind the NFS mount, or its mount-options.
* Do all users have `astro-apps6` as their _primary_ group, rather than just being a member of that group?
* Did `.git` certainly have SGID at the time the `.git/lfs` sub-directory was created?

**Comment by r-owen** [comment]
- I have no idea how to find the filesystem type behind the NFS mount.
- Both users have `astro-apps` as a group, but I doubt it is their primary group.
- The parent directory into which the repo was cloned certainly had SGID to start with. I do not know in what sequence git-lfs creates directories, so I am not sure that .git had SGID when .git/lfs was created, but it would surprise me if not. I would expect git to create the dir with all permissions set.

Has anyone tried this?

**Comment by javabrett** [comment]
Someone with shell-access to the NFS server should be able to check those mount options.  They may not be relevant anyway.

I think it is worth running a comparison-test with `astro-apps` as the primary-group of two different test-users.  There have been issues in the past where different NFS implementations have misbehaved in this regard.

It is also worth testing on a clean set-up, ensuring that the parent directory has the desired SGID settings before initializing LFS.

Finally, what appears when you directly from a shell `mkdir` or `touch` files in that `logs` directory, as a user that normally runs LFS - what group-ownership and permissions result?

This is starting to look more like a `umask` issue.

**Comment by r-owen** [comment]
We have repeatedly git cloned git-lfs repos into the parent directory that has SUID and we always see this problem. We also repeatedly git clone non-git-lfs repos without seeing this problem.

I can't touch a file in the .git/lfs directory because it was created with the wrong umask; the .git dir and all files are group writable, as they should be, but .git/lfs is not group writable.

Please try to reproduce this on another system. I'm assuming somebody has access to an nfs mounted volume and a test repo to try. The steps are trivial:
- Make sure umask is 002
- Create a directory with SUID set (though this probably doesn't matter)
- Clone a git-lfs repo into it
- Examine .git to see if .git/lfs is group writable. If it is not, but all other directories in .git are, then that's the bug

**Comment by javabrett** [comment]
Thanks for the detailed report.  Detail in [SO: Reading default FileMode when using os.O_CREATE](http://stackoverflow.com/questions/23842247/reading-default-filemode-when-using-os-o-create) might be relevant.

Looks like there's a number of `io` calls where the mode is set but is not `0666` - some or all of those might be OK, but need checking:

```
$ egrep -r "os\..*[0-9]{4}" *
Binary file bin/lfstest-gitserver matches
Binary file bin/git-credential-lfstest matches
Binary file bin/git-lfs-test-server-api matches
Binary file bin/git-lfs matches
Binary file bin/lfstest-testutils matches
commands/command_track.go:	attributesFile, err := os.OpenFile(".gitattributes", os.O_RDWR|os.O_APPEND|os.O_CREATE, 0660)
commands/commands.go:	if err := os.MkdirAll(lfs.LocalLogDir, 0755); err != nil {
commands/command_fsck.go:			if err := os.MkdirAll(badDir, 0755); err != nil {
lfs/http.go:	if err := os.MkdirAll(logBase, 0755); err != nil {
lfs/hook.go:	if err := os.MkdirAll(filepath.Join(LocalGitDir, "hooks"), 0755); err != nil {
lfs/pointer_smudge.go:	os.MkdirAll(filepath.Dir(filename), 0755)
lfs/util.go:	if err := os.MkdirAll(cbDir, 0755); err != nil {
lfs/util.go:	file, err := os.OpenFile(logPath, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0666)
lfs/pointer.go:	f, err := os.OpenFile(file, os.O_RDONLY, 0644)
lfs/progress_meter.go:	if err := os.MkdirAll(cbDir, 0755); err != nil {
lfs/progress_meter.go:	file, err := os.OpenFile(logPath, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0666)
localstorage/localstorage.go:	dirPerms os.FileMode = 0755
script/build.go:		err := os.MkdirAll(dir, 0755)
script/build.go:	if err := os.Chmod(fullInstallPath, 0755); err != nil {
test/git-lfs-test-server-api/main.go:	f, err := os.OpenFile(filename, os.O_RDONLY, 0644)
test/git-lfs-test-server-api/main.go:	f, err := os.OpenFile(filename, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644)
test/testutils.go:			os.MkdirAll(filepath.Dir(infile.Filename), 0755)
vendor/_nuts/github.com/rubyist/tracerx/tracerx.go:			tracerOut, err := os.OpenFile(trace, os.O_WRONLY|os.O_APPEND|os.O_CREATE, 0666)
vendor/_nuts/github.com/ThomsonReutersEikon/log4go/filelog.go:	fd, err := os.OpenFile(w.filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE, 0660)
vendor/_nuts/code.google.com/p/log4go/filelog.go:	fd, err := os.OpenFile(w.filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE, 0660)
```

```
$ grep -r localLogDirPerms *
lfs/lfs.go:	localLogDirPerms   = 0755
lfs/lfs.go:		if err := os.MkdirAll(LocalLogDir, localLogDirPerms); err != nil {
```

**Comment by brupm** [comment]
Any update on this?

**Comment by ryran** [comment]
The problem is that git-lfs is ignoring umask, effectively (or explicitly) removing group write permission when it's writing files to `.git/lfs/`.

NFS doesn't have anything to do with this, so don't waste time trying to chase that down. Primary group doesn't matter either. The point is: if you have an appropriate umask (or appropriate facls), the .git/lfs dir and everything in it should respect that .... but it's not.

E.g.:

```shell
mkdir gitprojects && cd gitprojects
chgrp collab .
# Add sgid to make sure everything gets owned by "collab" group
chmod 2770 .
# Set a default umask for the group categor
setfacl -m d:g::rwx .
# Since we did those two steps, it's not necessary to do this, but let's do it anyway:
setfacl -m d:g:collab:rwx .
# Finally, clone some lfs repo
git lfs clone xxxxxx
```
For each new project you clone, you'll see that all files are writable for the group "collab", except for everything in `.git/lfs`. Nonsense.

**Comment by ttaylorr** [comment]
Hi @ryran, thanks for this and sorry that it's taken me a little while to get back to you. Looking at where LFS creates the local storage directory (`.git/lfs/objects` and friends) as well as @javabrett's suggestion in https://github.com/git-lfs/git-lfs/issues/943#issuecomment-218614763, I created the following diff to ensure that the localstorage directory is created with octal mode `0666`:  

```diff
diff --git a/localstorage/localstorage.go b/localstorage/localstorage.go
index aec93eb0..80713800 100644
--- a/localstorage/localstorage.go
+++ b/localstorage/localstorage.go
@@ -15,7 +15,7 @@ const (
 
 var (
 	oidRE                = regexp.MustCompile(`\A[[:alnum:]]{64}`)
-	dirPerms os.FileMode = 0755
+	dirPerms os.FileMode = 0666
 )
 
 // LocalStorage manages the locally stored LFS objects for a repository.
```

I've built LFS with this patch applied (see: 0229fe0) and posted the binaries here. Can you give them a try for me and see if it works?

[git-lfs-darwin-386-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289071/git-lfs-darwin-386-2.3.0-pre.tar.gz)
[git-lfs-darwin-amd64-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289072/git-lfs-darwin-amd64-2.3.0-pre.tar.gz)
[git-lfs-freebsd-386-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289073/git-lfs-freebsd-386-2.3.0-pre.tar.gz)
[git-lfs-freebsd-amd64-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289069/git-lfs-freebsd-amd64-2.3.0-pre.tar.gz)
[git-lfs-linux-386-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289070/git-lfs-linux-386-2.3.0-pre.tar.gz)
[git-lfs-linux-amd64-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1289074/git-lfs-linux-amd64-2.3.0-pre.tar.gz)
[git-lfs-windows-386-2.3.0-pre.zip](https://github.com/git-lfs/git-lfs/files/1289075/git-lfs-windows-386-2.3.0-pre.zip)
[git-lfs-windows-amd64-2.3.0-pre.zip](https://github.com/git-lfs/git-lfs/files/1289076/git-lfs-windows-amd64-2.3.0-pre.zip)

**Comment by dmschlot** [comment]
We are also experiencing this issue. I don't know all the details of what is going on but doing my own digging I thought I'd share some information with people. If you look here: https://github.com/git-lfs/git-lfs/blame/master/config/config.go
You'll see a new getMask() function that was added. That new function uses the git config setting "core.sharedrepository". This function was added Oct 4th. That is after the current release (2.5.2). My GUESS (please correct me if you know better) is that a fix to this will be included in the next release, and it seems that fix is to use the "core.sharedrepository" setting when setting permissions on the ".git/lfs" folder and its contents.

**Comment by bk2204** [comment]
Yes, that commit is present in what will become 2.6.0.  It honors the `core.sharedrepository` setting, which includes honoring the umask by default.  2.6.0 is scheduled for release tomorrow.

**Comment by bk2204** [comment]
I will say that the change in 286ac6 will not handle ACLs properly.  Because we're creating a temporary file, which has its permissions set to 0600, we have to manually set the permissions on the file, and ACLs aren't honored in that case.  That's a limitation of the Go temporary file library that we use; we'd have to write our own to avoid that problem.

**Comment by mhorbul** [comment]
We are using version 2.6.1  of git-lfs on Centos 7. The `core.sharedrepository` does not seem to be considered when lfs/* folders and files are created. The parent folder has a Group SUID bit set, but the lfs folder is created group non-writable. 

### without core.sharedrepository config

```
[mhorbul@app01 repo]$ ls -al lfs
ls: cannot access lfs: No such file or directory
[mhorbul@app01 repo]$ umask 0002 && git archive mhorubl/lfs-testing > /dev/null 2>&1
[mhorbul@app01 repo]$ cat config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = true
[remote "origin"]
        url = git@github.com:mhorbul/app.git
        fetch = +refs/*:refs/*
        mirror = true
[mhorbul@admin-staging01 repo]$ ls -al lfs
total 0
drwxr-sr-x. 5 mhorbul deploy_staging  50 Jan 15 19:41 .
drwxrwsr-x. 8 dmytro  deploy_staging 167 Jan 15 19:41 ..
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:41 incomplete
drwxr-sr-x. 5 mhorbul deploy_staging  36 Jan 15 19:41 objects
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:41 tmp
```

### core.sharedrepository = group
```
[mhorbul@app01 repo]$ ls -al lfs
ls: cannot access lfs: No such file or directory
[mhorbul@app01 repo]$ git config core.sharedrepository "group"
[mhorbul@app01 repo]$ cat config | grep sharedrepo
        sharedrepository = group
[mhorbul@app01 repo]$ umask 0002 && git archive mhorubl/lfs-testing > /dev/null 2>&1
[mhorbul@app01 repo]$ ls -al lfs
total 0
drwxr-sr-x. 5 mhorbul deploy_staging  50 Jan 15 19:44 .
drwxrwsr-x. 8 dmytro  deploy_staging 167 Jan 15 19:44 ..
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:45 incomplete
drwxr-sr-x. 5 mhorbul deploy_staging  36 Jan 15 19:45 objects
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:45 tmp
```

### core.sharedrepository = all
```
[mhorbul@app01 repo]$ rm -rf lfs
[mhorbul@app01 repo]$ git config core.sharedrepository "all"
[mhorbul@app01 repo]$ ls -al lfs
ls: cannot access lfs: No such file or directory
[mhorbul@app01 repo]$ cat config | grep sharedrepo
        sharedrepository = all
[mhorbul@app01 repo]$ umask 0002 && git archive mhorubl/lfs-testing > /dev/null 2>&1
[mhorbul@admin-staging01 repo]$ ls -al lfs
total 0
drwxr-sr-x. 5 mhorbul deploy_staging  50 Jan 15 19:46 .
drwxrwsr-x. 8 dmytro  deploy_staging 167 Jan 15 19:46 ..
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:46 incomplete
drwxr-sr-x. 5 mhorbul deploy_staging  36 Jan 15 19:46 objects
drwxr-sr-x. 2 mhorbul deploy_staging   6 Jan 15 19:46 tmp
```

**Comment by bk2204** [comment]
Yes, I think that was an oversight which was corrected in #3417, which will be in Git LFS 2.7.0.

**Comment by bk2204** [comment]
I think this has been fixed in Git LFS 2.7.0 and newer. Could someone who's seen this problem confirm that this is working as expected for you now (excluding ACLs)?
